### ISSUE TITLE
[Question] Old (pre v2) static files still on server

### ISSUE THREAD

**Issue by willstocks** [SuperPWA/Super-Progressive-Web-Apps#100]
Originally logged: https://wordpress.org/support/topic/question-old-static-files-still-on-server/

Hi guys,

Obviously, since v2.0 the SW and manifest files are dynamically created, however I still have the pre-v2.0 files in my root on my server – so I’m unsure as to which file is winning and therefore being applied? I’m assuming the root file is overruling the dynamic file?

So my questions:

1. How can I check whether the dynamic file IS being generated?
1. Can I delete the files in my root or is there a way that I can choose between static files vs dynamic (on a lower powered server, it’d be nice to save the few extra cycles on every single visit for dynamic file generation)?
1. I have a site.webmanifest file where I have a few more lines applied than SuperPWA offers (primarily different icon sizes) – is there any way for me to hook into the dynamic file generation to add these extra image sizes myself (I want to make sure I’m using the latest version of the manifest structure ?
site.webmanifest:

```
    "icons": [
        {
            "src": "https://cdn.willstocks.com/wp-content/uploads/2018/10/android-chrome-36x36.png",
            "sizes": "36x36",
            "type": "image/png"
        },
        {
            "src": "https://cdn.willstocks.com/wp-content/uploads/2018/10/android-chrome-48x48.png",
            "sizes": "48x48",
            "type": "image/png"
        },
        {
            "src": "https://cdn.willstocks.com/wp-content/uploads/2018/10/android-chrome-72x72.png",
            "sizes": "72x72",
            "type": "image/png"
        },
        {
            "src": "https://cdn.willstocks.com/wp-content/uploads/2018/10/android-chrome-96x96.png",
            "sizes": "96x96",
            "type": "image/png"
        },
        {
            "src": "https://cdn.willstocks.com/wp-content/uploads/2018/10/android-chrome-144x144.png",
            "sizes": "144x144",
            "type": "image/png"
        },
        {
            "src": "https://cdn.willstocks.com/wp-content/uploads/2018/10/android-chrome-192x192.png",
            "sizes": "192x192",
            "type": "image/png"
        },
        {
            "src": "https://cdn.willstocks.com/wp-content/uploads/2018/10/android-chrome-256x256.png",
            "sizes": "256x256",
            "type": "image/png"
        },
		{
			"src": "https://cdn.willstocks.com/wp-content/uploads/2017/12/17144151/Will-Stocks-willstocks.co_.uk-New-Favicon.png",
			"sizes": "512x512",
			"type": "image\/png"
		}
    ]
```

superpwa-manifest.json (pre-v2):

```
	"icons": [
		{
			"src":"https:\/\/cdn.willstocks.com\/wp-content\/uploads\/2018\/10\/apple-touch-icon-precomposed.png",
			"sizes":"192x192",
			"type":"image\/png"
		},
		{
			"src":"https:\/\/cdn.willstocks.com\/wp-content\/uploads\/2017\/12\/17144151\/Will-Stocks-willstocks.co_.uk-New-Favicon.png",
			"sizes":"512x512",
			"type":"image\/png"
		}
	]
```

**Comment by Sanjeevsetu** [comment]
Closing the ticket due to inactivity. Still have an issue, Please create a new ticket or contact us.
