### ISSUE TITLE
Plan for pwa-wp feature plugin compatibility?

### ISSUE THREAD

**Issue by twaiiiin** [SuperPWA/Super-Progressive-Web-Apps#102]
Hello,

Do you intend to make your plugin compatible with this feature plugin (proposed for core merge)?

https://wordpress.org/plugins/pwa/
https://github.com/xwp/pwa-wp

> ☞ Please note that this feature plugin is not intended to obsolete the other plugins and themes which turn WordPress sites into PWAs. Rather, **this plugin is intended to provide the PWA building blocks and coordination mechanism for these themes and plugins to not reinvent the wheel and also to not conflict with each other**. For example, a theme that implements the app shell model should be able to extend the core service worker while a plugin that provides push notifications should be able to do the same. Themes and plugins no longer should have to each create a service worker on their own, something which is inherently problematic because only one service worker can be active at a time: only one service worker can win. If you are developing a plugin or theme that includes a service worker, consider relying on this PWA plugin, or at least only use the built-in implementation as a fallback for when the PWA plugin is not available.

Thank you.

**Comment by arunbasillal** [comment]
Of course. We are in touch with their team and actively following the project. 

We wanted to wait a bit longer so that we don't have to rework every time they make changes. Merging this to core is essential for service workers and PWA's, but not a small task. 

Thanks for the interest and love.
