### ISSUE TITLE
Not issue but wanted feature - Add sub URL to homescreen

### ISSUE THREAD

**Issue by fracii** [SuperPWA/Super-Progressive-Web-Apps#103]
Hi,

I want to add current URL to homescreen (mysite.com/abc/current-url-example) and not main URL like mysite.com on iOS and Android.

Any quick fix to add this feature. I was check little in code after **start_url**, but I think I mess things up if I make code-changes by myself.

Thx!

**Comment by Sanjeevsetu** [comment]
Closing the ticket due to inactivity. Still have an issue, Please create a new ticket or contact us.
