### ISSUE TITLE
superpwa-manifest.json is not served via HTTP/2

### ISSUE THREAD

**Issue by twaiiiin** [SuperPWA/Super-Progressive-Web-Apps#105]
Hello there,

Google Lighthouse tells me that the superpwa-manifest.json file is not served by HTTP/2 while the other resources are. Is this normal? Do you have the same behavior on other website?

It looks like all requests that are served from the Service Worker are marked with HTTP/1.1. This could be a bug with Google Chrome & Lighthouse (https://github.com/GoogleChrome/lighthouse/issues/7158) but it also affect on Firefox, too.

Thank you.

**Comment by siwalikm** [comment]
I faced the same issue earlier today. The lighthouse bug you referenced is fixed but hasn't reached stable browsers yet. Try checking using the lighthouse chrome extension or on chrome canary.

[Here's the link to that PR. ](https://github.com/GoogleChrome/lighthouse/pull/7197)

**Comment by Sanjeevsetu** [comment]
Hi @twaiiiin 

I am closing the ticket. If You still have issues, Please create new ticket or contact us
