### ISSUE TITLE
OneSignal admin notices can be removed

### ISSUE THREAD

**Issue by phlegx** [SuperPWA/Super-Progressive-Web-Apps#114]
With the new version 2.0.1 of OneSignal Wordpress plugin, this notices can be removed:

- https://github.com/SuperPWA/Super-Progressive-Web-Apps/blob/05ef8b38344cebd9c9575d01ea471666f7c8c3f0/3rd-party/onesignal.php#L50
- https://github.com/SuperPWA/Super-Progressive-Web-Apps/blob/05ef8b38344cebd9c9575d01ea471666f7c8c3f0/3rd-party/onesignal.php#L51

The plugin author of OneSignal - Web Push Notifications confirms, that Web Push does not require a manifest.json file anymore, so it has removed that from settings and from his SDK.

- https://wordpress.org/support/topic/setting-own-manifest-gone/

**Related issue:** 

- [OneSignal-WordPress-Plugin/issues/235](https://github.com/OneSignal/OneSignal-WordPress-Plugin/issues/235)
- [OneSignal-WordPress-Plugin/issues/218](https://github.com/OneSignal/OneSignal-WordPress-Plugin/issues/218)

**Comment by josevarghese** [comment]
Hello @phlegx 

A quick fix is available to download at: https://github.com/SuperPWA/Super-Progressive-Web-Apps/releases/tag/2.0.2.1
