### ISSUE TITLE
Modify Startup Font

### ISSUE THREAD

**Issue by Piket564** [SuperPWA/Super-Progressive-Web-Apps#116]
Hi, is possible to modify the sturtup font when i've added the app on my device?
The app name is placed bottom with a different font, i wish i can change it with one of my website.

Any suggestion will be accepted!

**Comment by Sanjeevsetu** [comment]
Hi @Piket564 

Since than we have improved a lot. You should try our latest version. If You still have an issue or need more help, Please create a new ticket or contact us. I am closing the ticket due to inactivity.
