### ISSUE TITLE
Precache function or hook?

### ISSUE THREAD

**Issue by mlangone** [SuperPWA/Super-Progressive-Web-Apps#119]
Is there a function or hook to set a list of urls to precache? Also the  start_url does not respond via the service worker.

Thanks
<img width="759" alt="Screen Shot 2020-03-19 at 11 47 07 PM" src="https://user-images.githubusercontent.com/4027703/77142070-3fd92980-6a3c-11ea-975f-623b409253fc.png">

**Comment by syedimran22** [comment]
Hi @mlangone 

Could you send us your site url to check start_url error in the lighthouse

**Comment by syedimran22** [comment]
This issue is still in debugging mode once the issue is found we can reopen this ticket
