### ISSUE TITLE
Generated Manifest.json is not being read

### ISSUE THREAD

**Issue by Celestz** [SuperPWA/Super-Progressive-Web-Apps#12]
Hi, I tried using your plugin and encountered a weird issue, not sure if this is in your ballpark or should I raise this to Chromium, but the manifest file isn't read, I checked the format, but since it's generated it shouldn't have any issue.

https://rumbleroyale.gg/ <- Check this site for the details, service workers got generated just fine.

**Comment by arunbasillal** [comment]
Hello @Celestz 

Can you try this as a test? I have seen this on a couple of sites so far - https://www.dropbox.com/s/3xntsbcfr5hctq5/super-progressive-web-apps-1.5-beta.zip?dl=0

**Comment by josevarghese** [comment]
Hello @Celestz,
I tested your website on Chromium Browser (Latest Version : 67.0.3369.0) and seems like all the features of PWA are working perfectly. 

Can you please confirm whether you have cleared the cache upon browser before testing? If not, please clear it and check it again. 

Hope it will surely helps.

Thanks!
Jose

**Comment by arunbasillal** [comment]
@Celestz I just checked and everything is working as expected. Closing this issue, feel free to revert if you have any questions.
