### ISSUE TITLE
Action Required to integrate SuperPWA with OneSignal

### ISSUE THREAD

**Issue by Officialhackercommunity** [SuperPWA/Super-Progressive-Web-Apps#121]
I am running SuperPWA version 2.0.2 and OneSignal Notification version 2.1.2 after after the updates of both plugins i am still counter an error its shows me to . ##Enable Use my own manifest.json in advance settings

**Comment by josevarghese** [comment]
Hi,

You can try out the quick fix available at [here](https://github.com/SuperPWA/Super-Progressive-Web-Apps/releases/tag/2.0.2.1), which will remove the admin notice. The version which is available to GitHub 2.0.2.1 will resolve the admin error notice message showing with respect to the latest OneSignal plugin. For more details on why the error message is showing over the 2.0.2 version of SuperPWA, take a look into this [ article ](https://superpwa.com/doc/setup-onesignal-with-superpwa/) with all that you want to know.

Hope that will help you :)
