### ISSUE TITLE
Automatically exclude /superpwa-sw.js & /superpwa-manifest.json from being cached by WP Rocket

### ISSUE THREAD

**Issue by arunbasillal** [SuperPWA/Super-Progressive-Web-Apps#125]
If these files are dynamic, WP Rocket will cache these files leading to `unsupported MIME type error`. 

Related issue - https://github.com/wp-media/wp-rocket/issues/2778

Since it's best to add the exclusions at our end, let's do it like that.

**Comment by syedimran22** [comment]
As I have tested so there is no issue which is reported as of now if it occurs we will reopen this ticket
