### ISSUE TITLE
Please add compatibility with Webpushr WordPress Plugin

### ISSUE THREAD

**Issue by webpushr** [SuperPWA/Super-Progressive-Web-Apps#129]
[Webpushr](https://wordpress.org/plugins/webpushr-web-push-notifications/) is the fastest growing Web Push Plugin for WordPress sites. Unfortunately at this time, Webpushr & SuperPWA plugin are not compatible with each other as only one service worker file can be activated per root domain. This leaves ALOT of our customers having to select one or the other. Can you please add compatibility with Webpushr, similar to how you support OneSignal in your next release? The solution is similar to how you have solved it with OneSignal: by combining our two separate Service Worker files into a new single file placed in the root folder (example: domainname.com/webpushr-sw.js.php) that contains the following: 

```
importScripts('https://cdn.webpushr.com/sw-server.min.js'); 
/**
 * Contents of SuperPWA Service Worker file here
 */
```

Related posts: 
[https://wordpress.org/support/topic/compatibility-with-other-pwa/](https://wordpress.org/support/topic/compatibility-with-other-pwa/)
[https://wordpress.org/support/topic/add-support-for-webpushr/](https://wordpress.org/support/topic/add-support-for-webpushr/)

**Comment by josevarghese** [comment]
Thanks for sharing the details.

**Comment by miqueasgutierrez** [comment]
Hello do not complicate install the plugin
INDIGITALL, works great and is very easy to install:
1-In the left side menu, click on Plugins> Add new
2-Use the search bar located at the top right to find our plugin by typing the word indigitall:
3-Click on Install now and then activate the plugin by clicking on Activate.
4-If everything went well, you will be redirected to the plugin settings to finish the integration on your WordPress website.

**Comment by donbowman** [comment]
seems we just need to copy+modify https://github.com/SuperPWA/Super-Progressive-Web-Apps/blob/master/3rd-party/onesignal.php.
Only question, what is the gcm sender id to use for webpushr?

**Comment by ajeetku** [comment]
Compatibility added in [webpushr](https://wordpress.org/plugins/webpushr-web-push-notifications/#description) plugin
