### ISSUE TITLE
superpwa-manifest.json taking a long time to load

### ISSUE THREAD

**Issue by zuvius** [SuperPWA/Super-Progressive-Web-Apps#130]
Can you please help why the superpwa-manifest.json is taking 5 seconds on the page loading as mentioned by Gtmetrix? I have tried the solution given on https://wordpress.org/support/topic/superpwa-json-taking-a-long-time-to-load/, but it's not working!

**Comment by ajeetku** [comment]
@zuvius kindly share URL so we can check the use case and resolve it

**Comment by ajeetku** [comment]
Released in 2.1.8
