### ISSUE TITLE
Wrong site url, 404 on default page

### ISSUE THREAD

**Issue by diego-betto** [SuperPWA/Super-Progressive-Web-Apps#134]
Hi,

It seems that you use `ABSPATH` to get "root" folder for example [here](https://github.com/SuperPWA/Super-Progressive-Web-Apps/blob/1300d162a0616da5d5d548667e9f045fbae8d252/public/manifest.php#L71)

But if you have installed WordPress in a sub-folder and you use rewrite + `index.php` in the root folder with this change (added `site/`)
```PHP
/** Loads the WordPress Environment and Template */
require( dirname( __FILE__ ) . '/site/wp-blog-header.php' );
```

 `ABSPATH` will return a wrong path. 
Please check [`get_home_path()`](https://wordpress.stackexchange.com/questions/188448/whats-the-difference-between-get-home-path-and-abspath).

**Comment by ajeetku** [comment]
Solution Released in Version 2.1.4
