### ISSUE TITLE
Add option to enable PWA just for specific pages

### ISSUE THREAD

**Issue by DJIronic** [SuperPWA/Super-Progressive-Web-Apps#135]
Hello!

I need to make a PWA just from  a specific page. Please make that possible, thank you!

**Comment by dmassey-vertex** [comment]
Bump

**Comment by Sanjeevsetu** [comment]
Related https://github.com/SuperPWA/Super-Progressive-Web-Apps/issues/429. This feature is coming in next SuperPWA pro version release.
