### ISSUE TITLE
PWA doesn’t work

### ISSUE THREAD

**Issue by AndrewSukhenko** [SuperPWA/Super-Progressive-Web-Apps#137]
Hi! I have some issues with your plugin:

1. When I try to change something in settings and click “save” it writes me that my changes have been saved but actually not
2. My manifest file is blank https://www.pizzahata.com.ua/superpwa-manifest.json

My topic on forum - https://wordpress.org/support/topic/pwa-doesnt-work-2/

**Comment by ajeetku** [comment]
@AndrewSukhenko As we checked on our side all options are saving properly. Can you please share some screenshot of options which is not saving.

**Comment by ajeetku** [comment]
If you still facing the same issue.
Our team will help you with these on https://superpwa.com/contact/
