### ISSUE TITLE
Default Add to home screen banner is not showing

### ISSUE THREAD

**Issue by JNAzeem** [SuperPWA/Super-Progressive-Web-Apps#140]
WordPress Ref: https://wordpress.org/support/topic/add-to-home-screen-is-not-showing/
https://wordpress.org/support/topic/add-to-home-page-pro-feature-in-2-1-3/

URL links: https://tester.santaluciaexperiencias2020.com/
https://cc2bd8f09bb88b5dd20f9b432631b8ca.rangoabzar.com/

**Comment by namishsaxena** [comment]
Thanks for working on this. Do you have a timeline for this. I am having the same issue.

**Comment by ajeetku** [comment]
Solution released in version 2.1.4
