### ISSUE TITLE
Changes in Presentation

### ISSUE THREAD

**Issue by supernation** [SuperPWA/Super-Progressive-Web-Apps#141]
- [x] Remove https://take.ms/VF8I2

- [x] Add two new pro features in the feature section with read more link to tutorials like https://take.ms/6uZqJ

- [x] Add this: https://take.ms/hlzS7

- [x] Add this https://take.ms/hPAsk after first paragraph but with these links
Home  |  Documentation  |  Help  |  Premium version Features

**Comment by ajeetku** [comment]
Released in Version 2.1.4
