### ISSUE TITLE
Need to add tutorial link for Call To Action and Android APK APP Generator	

### ISSUE THREAD

**Issue by sonaliramteke** [SuperPWA/Super-Progressive-Web-Apps#145]
Need to add tutorial link for Call To Action and Android APK APP Generator	
Ref: https://prnt.sc/w5d7yp
This is the tutorial link for Call To Action - https://superpwa.com/doc/call-to-action-cta-add-on-for-superpwa/
This is the tutorial link for Android APK APP Generator	- https://superpwa.com/doc/android-apk-app-generator-add-on-for-superpwa/

**Comment by ajeetku** [comment]
Released in version 2.1.5
