### ISSUE TITLE
Support for Yandex manifest

### ISSUE THREAD

**Issue by JNAzeem** [SuperPWA/Super-Progressive-Web-Apps#146]
WordPress ref: https://wordpress.org/support/topic/support-for-yandex-manifest/
site URL link: https://turboapps.yandex.ru/console/check-manifest
manifest file: https://beltrud.ru/superpwa-manifest.json
API: https://yandex.ru/dev/turboapps/doc/dev/manifest.html

**Comment by ajeetku** [comment]
Need some clarification from user

**Comment by ajeetku** [comment]
Released in version 2.1.5
