### ISSUE TITLE
Quick action feature for PWA

### ISSUE THREAD

**Issue by JNAzeem** [SuperPWA/Super-Progressive-Web-Apps#147]
WordPress Forum : https://wordpress.org/support/topic/feature-app-shortcuts/

https://web.dev/app-shortcuts/

**Comment by ajeetku** [comment]
Released in version 2.1.5

**Comment by ajeetku** [comment]
User can add multiple shortcodes,
Give more options to add other details (not automated) like icon, title, description,
add documentation link over the field,
update documentation https://superpwa.com/doc/app-shortcuts-link-in-super-pwa/ add here output screenshot of shortcut.

**Comment by ajeetku** [comment]
For more features (like ) created https://github.com/SuperPWA/Super-Progressive-Web-Apps/issues/163

**Comment by ajeetku** [comment]
Current feature released in 2.1.6 with a single shortcut link
