### ISSUE TITLE
CTA banner is not displayin in ios

### ISSUE THREAD

**Issue by TMsravan** [SuperPWA/Super-Progressive-Web-Apps#148]
https://secure.helpscout.net/conversation/1373074649/171281?folderId=2632030

Cta banner is not displaying in ios. 

https://www.futsalescocia.co.uk/

![image](https://user-images.githubusercontent.com/46995400/103078961-f89a4d80-45f8-11eb-9e6c-61f390936a02.png)

**Comment by ajeetku** [comment]
updated in version 1.1 SuperPWA PRO
