### ISSUE TITLE
Disabling "Add to home screen"

### ISSUE THREAD

**Issue by beatsk** [SuperPWA/Super-Progressive-Web-Apps#150]
Is it possible somehow disable this feature?

**Comment by ajeetku** [comment]
Released in version 2.1.5

**Comment by beatsk** [comment]
Hi.

I've tried it, but the banner is still showing. Website cache cleared, phone and dekstop, too.

**Comment by ajeetku** [comment]
@beatsk solution working as we have checked, please clear server-side and CND (if you are using) also.
If still facing this issue please contact us at https://superpwa.com/contact/
