### ISSUE TITLE
Assetlink.json deploy for multi website

### ISSUE THREAD

**Issue by TMsravan** [SuperPWA/Super-Progressive-Web-Apps#151]
https://secure.helpscout.net/conversation/1382298499/172882?folderId=1060556

Assetlink.json deploy for multi-website

Use case: The user is using multisite and the issue is URL on the top is getting displayed in the app and he wants to generate the apk files for multiple websites and using one single WordPress installation

**Comment by ajeetku** [comment]
Associating a website with multiple apps (In answer to "display assetlinks.json when the multisite on the same installation")
The following file listing shows an example of a statement file that declares an association with two apps, separately, and resides at https://domain.name/.well-known/assetlinks.json:

`[{
  "relation": ["delegate_permission/common.handle_all_urls"],
  "target": {
    "namespace": "android_app",
    "package_name": "com.example.puppies.app",
    "sha256_cert_fingerprints":
    ["14:6D:E9:83:C5:73:06:50:D8:EE:B9:95:2F:34:FC:64:16:A0:83:42:E6:1D:BE:A8:8A:04:96:B2:3F:CF:44:E5"]
  }
  },
  {
  "relation": ["delegate_permission/common.handle_all_urls"],
  "target": {
    "namespace": "android_app",
    "package_name": "com.example.monkeys.app",
    "sha256_cert_fingerprints":
    ["14:6D:E9:83:C5:73:06:50:D8:EE:B9:95:2F:34:FC:64:16:A0:83:42:E6:1D:BE:A8:8A:04:96:B2:3F:CF:44:E5"]
  }
}]`

**Comment by ajeetku** [comment]
Closing this thread,
