### ISSUE TITLE
Need to create an analytics to show how many people have installed the site application to their phone

### ISSUE THREAD

**Issue by kunalaharika** [SuperPWA/Super-Progressive-Web-Apps#152]
Need to create an option to show how many people have installed the site application to their phone.

Ref:https://secure.helpscout.net/conversation/1380671611/172598?folderId=3575684

**Comment by akashagrjsr** [comment]
One more user-requested for this:
Ref: https://secure.helpscout.net/conversation/1419446954/179823?folderId=2770545

**Comment by syedimran22** [comment]
Released in SuperPWA Pro Plugin of Version **1.5**
