### ISSUE TITLE
Disabling ads for app

### ISSUE THREAD

**Issue by ghost** [SuperPWA/Super-Progressive-Web-Apps#155]
Hello,

Is there a option to block ads, exclusively only for PWA? In case someone wants to upload the application to Google Play, because adsense ads are prohibited. (Maybe I am wrong)

**Comment by supernation** [comment]
@beatsk pls send us the more details on https://superpwa.com/contact/

so I can understand and help you with this

**Comment by supernation** [comment]
@beatsk did you sent the user scenario?

**Comment by Sanjeevsetu** [comment]
Hi @ghost

Please contact us through above contact form
