### ISSUE TITLE
Need to Add the functionality for adding ADD to Home screen button by using Short code.

### ISSUE THREAD

**Issue by TMsravan** [SuperPWA/Super-Progressive-Web-Apps#156]
Use case: A SuperPWA shortcode would allow site owners to post the install link however and wherever they want. This would give them much more control over prompting their users to install the PWA.

Ref: https://secure.helpscout.net/conversation/1388324421/174167?folderId=2632030

**Comment by facultidev42FacultiDevelopment** [comment]
hi, do you know if the shortcode may be viable?

**Comment by ajeetku** [comment]
Released in PRO version 1.3
