### ISSUE TITLE
If the "Show on Desktop CTA" option is disabled then also the CTA bar is showing on the desktop

### ISSUE THREAD

**Issue by akashagrjsr** [SuperPWA/Super-Progressive-Web-Apps#158]
Ref: https://secure.helpscout.net/conversation/1401438679/176401?folderId=2770545

Screenshots:
https://prnt.sc/xfh7sm

https://prnt.sc/xfh9iu

The issue is also occurring on the local.

User site: https://cuteberry.de/

**Comment by ajeetku** [comment]
https://github.com/SuperPWA/Super-Progressive-Web-Apps/issues/157 Duplicate ticket
