### ISSUE TITLE
Splash Image / BG

### ISSUE THREAD

**Issue by lawtonj404** [SuperPWA/Super-Progressive-Web-Apps#160]
Splash screen/ icon not showing on IOS devices.

example: support.hixongroup.com, cloudhostpro.co.uk

Both examples show manifest & service worker ticks on admin page but both just show a white screen instead of splash screen logo.

**Comment by supernation** [comment]
pls contact the dev team via https://superpwa.com/contact/

**Comment by ajeetku** [comment]
Released in 2.1.7
