### ISSUE TITLE
Operating mode of the status bar on iOS

### ISSUE THREAD

**Issue by JNAzeem** [SuperPWA/Super-Progressive-Web-Apps#167]
WordPress ref: https://wordpress.org/support/topic/it-just-lacks-one-option-for-ios/
Documentation ref: https://medium.com/appscope/changing-the-ios-status-bar-of-your-progressive-web-app-9fc8fbe8e6ab

**Comment by ajeetku** [comment]
https://github.com/SuperPWA/Super-Progressive-Web-Apps/issues/210 same request

**Comment by syedimran22** [comment]
Released in Version : 2.1.17
