### ISSUE TITLE
The PWA CTA shortcode not working on the IOS devices for some users.

### ISSUE THREAD

**Issue by akashagrjsr** [SuperPWA/Super-Progressive-Web-Apps#171]
Ref: https://secure.helpscout.net/conversation/1397017652/175681?folderId=2770545

The PWA CTA shortcode not working on the IOS devices for some users due to some JS not loading properly. When the user clicks on the button he is not able to get the popup.

**Comment by ajeetku** [comment]
Pro commit: 6e6bb50
For Version 1.5
