### ISSUE TITLE
The text related to the PWA CTA are not related due to WPML

### ISSUE THREAD

**Issue by akashagrjsr** [SuperPWA/Super-Progressive-Web-Apps#172]
Ref: https://secure.helpscout.net/conversation/1447543383/184700?folderId=2770545

The text related to the PWA CTA is not related due to WPML after changing the language. The user did some changes to the code. I added the file and the screenshot related to it.

Screenshot: https://prnt.sc/10ivjl0

[cta code.zip](https://github.com/SuperPWA/Super-Progressive-Web-Apps/files/6123319/cta.code.zip)

**Comment by syedimran22** [comment]
Pro Commit: #282d657
Released in Version : 1.8
