### ISSUE TITLE
Chrome has improved the PWA offline detection

### ISSUE THREAD

**Issue by laharikakuna** [SuperPWA/Super-Progressive-Web-Apps#174]
Chrome has improved the PWA offline detection

https://developer.chrome.com/blog/improved-pwa-offline-detection/

Ref screenshot:https://prnt.sc/10pqi34

Ref URL: https://guides-guide.org/

Ref: https://secure.helpscout.net/conversation/1456714821/186628/

**Comment by Sasirekhamarella** [comment]
This user also facing the same installability issue.

Ref screenshot: https://prnt.sc/10pq48t
Website URL: https://www.quantumleap.asia/
Ref user Ticket:  https://wordpress.org/support/topic/installability

**Comment by Sasirekhamarella** [comment]
This user also getting the same errors.

Ref ticket: https://wordpress.org/support/topic/warning-page-doesnt-work-offline/#post-14231671
website URL: https://massapothecary.com/
Issue screenshot : https://massapothecary.com/

**Comment by syedimran22** [comment]
This Issue is occurring at strange scenario need to debug it first thoroughly
