### ISSUE TITLE
Fetch error and PWA Offline detection

### ISSUE THREAD

**Issue by willstocks** [SuperPWA/Super-Progressive-Web-Apps#176]
Hi team,

I've been using SuperPWA for a while now and it has appeared to work really well up until recently.

I'm running 2.1.8 + Caching Strategies add-on (network first) and I'm seeing the following console errors:

![image](https://user-images.githubusercontent.com/43744514/113126377-7af56780-920f-11eb-8071-14f5e27d73ad.png)

```
SuperPWA service worker ready

The FetchEvent for "https://willstocks.co.uk/" resulted in a network error response: the promise was rejected.
Promise.then (async) (anonymous) @ superpwa-sw.js:formatted:46

superpwa-sw.js:1 Uncaught (in promise) TypeError: Failed to fetch
```

Finally, I have also been seeing this in LightHouse reports and console for a few weeks now (although have ignored it):

```
(index):1 Site cannot be installed: Page does not work offline. Starting in Chrome 93, the installability criteria is changing, and this site will not be installable. See https://goo.gle/improved-pwa-offline-detection for more information.
```

**Comment by syedimran22** [comment]
Hi @willstocks 

I have checked your site and service worker is working perfectly without any error screenshot : https://ibb.co/FhcrYSx
If you are still facing the error can you send me your lighthouse report

**Comment by syedimran22** [comment]
This issue is still in debugging mode once the issue is found we can reopen this ticket
