### ISSUE TITLE
iOS popup message field's Translation is not working as per the users desired Language.

### ISSUE THREAD

**Issue by sardarui** [SuperPWA/Super-Progressive-Web-Apps#186]
One of our users is having the Swedish language on his site and he is adding the Swedish massage in the iOS pop message Field.

Screenshot: https://monosnap.com/direct/8oKGqeKD1iCoZP6mvpTuKIGA1Y2B22
Test Site: https://monosnap.com/direct/orrCG18Hhge45hjisPU8qfTD46tCvk

But it is not translating in the iOS device:
Screenshot: https://monosnap.com/direct/Nig2RQjwqJBOziV6xL5giU6U3nWTwp
Test Site: https://monosnap.com/direct/IP3BKcF8piBHcYvcTYkzlTRvwPnbp0

Ref Ticket: https://secure.helpscout.net/conversation/1506678380/195261?folderId=3126461

**Comment by syedimran22** [comment]
Committed in Pro Version  : 979c992

**Comment by syedimran22** [comment]
Released in SuperPWA PRO Version ; 1.6
