### ISSUE TITLE
Compatibility with wonder push

### ISSUE THREAD

**Issue by sonaliramteke** [SuperPWA/Super-Progressive-Web-Apps#188]
User Comment - Hi Team, I think wonderpush.com would be a good alternative for many users, especially within the E.U. Are you planning to support this or could you maybe provide a how-to concerning integration with this? They already explain how to use external service workers here, but I think it is still a bit too hard to understand for users like me. 🙂 https://docs.wonderpush.com/docs/service-worker-integration

**Comment by syedimran22** [comment]
Released in SuperPWA Version : 2.2.2
