### ISSUE TITLE
 CTA is not working properly in  ios chrome and ios safari

### ISSUE THREAD

**Issue by TMsravan** [SuperPWA/Super-Progressive-Web-Apps#189]
No action when we click on the CTA bar in ios chrome and ios safari 

Ref: https://www.boxingnewsandviews.com/

https://secure.helpscout.net/conversation/1519153814/197154?folderId=1060556

**Comment by syedimran22** [comment]
Committed in Pro : #d25582d

**Comment by syedimran22** [comment]
Released in SuperPWA PRO Version ; 1.6
