### ISSUE TITLE
IOS Splash Screens Image in not getting save

### ISSUE THREAD

**Issue by TMsravan** [SuperPWA/Super-Progressive-Web-Apps#191]
IOS Splash Screens Image is not getting save, in the Apple Touch Icons & Splash Screen extension.

Issue checked in the local as well.

Ref: https://secure.helpscout.net/conversation/1519153814/197154?folderId=2632030

https://monosnap.com/file/reAytZBKAmViy6Rr1RFJNy8IZycQDJ

https://magazine3.com/garage/wp-admin/admin.php?page=superpwa-apple-icons

**Comment by sardarui** [comment]
Another user is reporting the same: https://secure.helpscout.net/conversation/1524064053/198608/

**Comment by kupveja** [comment]
Another user is reporting the same - https://secure.helpscout.net/conversation/1527037034/199117?folderId=4459751

**Comment by syedimran22** [comment]
Released In Version : 2.1.13
