### ISSUE TITLE
Need an option to add the title name for the shortcode on CTA Addon.

### ISSUE THREAD

**Issue by kupveja** [SuperPWA/Super-Progressive-Web-Apps#198]
Need an option to add the title name for the shortcode on CTA Addon.

For example - If someone have added a button via shortcode, so the default title of the button will be " INSTALL APP " and there is no option to edit the title of this button on our CTA addon.
screenshot - https://prnt.sc/15in5c0

ref: https://secure.helpscout.net/conversation/1542597153/202006?folderId=4459751

**Comment by syedimran22** [comment]
Committed in PRO : #aef1e0d
Released SuperPWA PRO Version : 1.7
