### ISSUE TITLE
iOS App Store Package generator (IPA)

### ISSUE THREAD

**Issue by ghost** [SuperPWA/super-progressive-web-apps#199]
iOS APP Generator like the Android APK APP Generator component

Ref: https://secure.helpscout.net/conversation/1537328025/201270?folderId=2632030

**Comment by sajandara** [comment]
Another user is requesting this functionality.
https://magazine3.in/conversation/209417?folder_id=27

**Comment by gheriany** [comment]
I see that this ticket is over 2 years old and apparently nothing has been done about it! Any hope this will be addressed in the near future?

**Comment by Sanjeevsetu** [comment]
Related To https://github.com/SuperPWA/super-progressive-web-apps/issues/516

Hi @gheriany

We have added this feature to our latest pro version. You can contact our support for more info. https://superpwa.com/contact/
