### ISSUE TITLE
[Feature Request] Push notifications when new posts are published?

### ISSUE THREAD

**Issue by raveesh-me** [SuperPWA/Super-Progressive-Web-Apps#20]
We are in PWA domain now, so would it not be wonderful to have push notifications when new posts are published, done automatically?

**Comment by josevarghese** [comment]
Hello @raveesh-me, 

Good day! We're on the final tests to release our **next version 1.6** which will supports OneSignal (fully). As within OneSignal, you can easily and automatically push notifications once you publish new posts.

Thanks,
Jose
SuperPWA

**Comment by raveesh-me** [comment]
Amazing

**Comment by raveesh-me** [comment]
Amazing! Closing this issue!
