### ISSUE TITLE
User end issue: Apple splash icon not working properly.

### ISSUE THREAD

**Issue by amer07** [SuperPWA/Super-Progressive-Web-Apps#200]
Ref:https://secure.helpscout.net/conversation/1531412175/200073?folderId=2770543

**Comment by syedimran22** [comment]
commit: https://github.com/SuperPWA/Super-Progressive-Web-Apps/commit/174c67f7ded83a5ebd8c93b156750aab4efaf634

**Comment by syedimran22** [comment]
Released In Version : 2.1.15
