### ISSUE TITLE
Need to add menu button option.

### ISSUE THREAD

**Issue by amer07** [SuperPWA/Super-Progressive-Web-Apps#204]
Ref:https://secure.helpscout.net/conversation/1560525051/205006?folderId=2770543

Need to add a menu button option like this https://monosnap.com/file/ZufrLg1Np5aQllxsFotm8qRYXpiVBb

**Comment by syedimran22** [comment]
Committed in SuperPWA PRO : #fe1c759

**Comment by syedimran22** [comment]
Released in SuperPWA PRO Version : 1.9
