### ISSUE TITLE
"Centralize Image with Background Color" and "Background Colour" both settings are not getting updated even after clicking of  "save settings" button.

### ISSUE THREAD

**Issue by laharikakuna** [SuperPWA/Super-Progressive-Web-Apps#205]
"Centralize Image with Background Color" and "Background Colour" both settings are not getting updated even after clicking of  "save settings" button.

Ref: https://secure.helpscout.net/conversation/1562669612/205247?folderId=3575684

**Comment by syedimran22** [comment]
Released In Version : 2.1.15
