### ISSUE TITLE
User's end issue - Error code is getting displayed above the CTA button on the front end.

### ISSUE THREAD

**Issue by kupveja** [SuperPWA/Super-Progressive-Web-Apps#207]
Error code is getting displayed above the CTA button on the front end.

ref - https://secure.helpscout.net/conversation/1565370400/205462?folderId=4459751

screenshot ref - https://prnt.sc/1agtldz

**Comment by syedimran22** [comment]
Committed In PRO : #2f7df22

**Comment by syedimran22** [comment]
Released in Version : 1.8
