### ISSUE TITLE
Add Notification badge on the PWA icon

### ISSUE THREAD

**Issue by JNAzeem** [SuperPWA/Super-Progressive-Web-Apps#212]
User want notification badge(number of notifications) on the PWA icon 

Helpscout: https://secure.helpscout.net/conversation/1591216327/208799?folderId=4544752
Ref: https://developer.mozilla.org/en-US/docs/Web/API/ServiceWorkerRegistration/showNotification

**Comment by mohammed-qutubuddin** [comment]
Helpscout: https://secure.helpscout.net/conversation/1618127481/211788?folderId=1060556
One more user request for it.

**Comment by Sanjeevsetu** [comment]
When there is any notification, PWA need to show badge on Icon of PWA.

Reference ticket -: https://magazine3.in/conversation/162721?folder_id=23

reference link -: https://developer.mozilla.org/en-US/docs/Web/Progressive_web_apps/How_to/Display_badge_on_app_icon

**Comment by sajandara** [comment]
Another user requires this functionality: https://magazine3.in/conversation/192698?folder_id=27
