### ISSUE TITLE
Need to make APK compatible with Android 11

### ISSUE THREAD

**Issue by laharikakuna** [SuperPWA/Super-Progressive-Web-Apps#214]
Getting issue while uploading APK on play store with new android 11, need to add API level 30

https://developer.android.com/about/versions/11
https://android-developers.googleblog.com/2020/11/new-android-app-bundle-and-target-api.html/

Following changes related to android 11
https://developer.android.com/about/versions/11/behavior-changes-11#change-details

Ref: https://secure.helpscout.net/conversation/1600342548/209769?folderId=3575684.

**Comment by syedimran22** [comment]
Issue has been in the Server End.

https://www.awesomescreenshot.com/image/12719033?key=21dbda880cc51d3d1504b6924ea72615
