### ISSUE TITLE
get error superpwa-sw.js:88 Uncaught (in promise) TypeError: Failed to execute 'put'

### ISSUE THREAD

**Issue by asd3427** [SuperPWA/Super-Progressive-Web-Apps#217]
superpwa-sw.js:88 Uncaught (in promise) TypeError: Failed to execute 'put' on 'Cache': Partial response (status code 206) is unsupported
    at superpwa-sw.js:88
i my website i get this error  how to fix this?!  is that im use wp-supercatch make this fail???
![QQ截图20210907225257](https://user-images.githubusercontent.com/34855528/132366110-ca66d207-9b77-4581-8a6d-d811160e25d9.png)

# [#``]([url](url))

**Comment by syedimran22** [comment]
For More updates regarding this issue follow this ticket #220
