### ISSUE TITLE
Need to make compatibility with Amp official

### ISSUE THREAD

**Issue by ankit644** [SuperPWA/Super-Progressive-Web-Apps#218]
Reference Ticket: https://secure.helpscout.net/conversation/1621638990/212120/
User has an amp site in standard mode and he is also using superpwa but in that service worker is not working as the js files are not loading in the amp site
Reference Screenshot: https://prnt.sc/1rk8ptt

**Comment by syedimran22** [comment]
Released in Version: 2.2
