### ISSUE TITLE
Need to add a feature to create different manifest for admin panel compared to frontend

### ISSUE THREAD

**Issue by raza-web** [SuperPWA/Super-Progressive-Web-Apps#221]
Helpscout link - https://secure.helpscout.net/conversation/1626090512/212492?folderId=4626537

Description - Would like the Add to Homescreen to be saved for that specific page, so that when the client goes to open the link from their phone, it would take them to that specific page.

**Comment by Sanjeevsetu** [comment]
Closing the ticket due to inactivity. Still have an issue, Please create a new ticket or contact us.
