### ISSUE TITLE
Wrong splash screen loading in APK.

### ISSUE THREAD

**Issue by amer07** [SuperPWA/Super-Progressive-Web-Apps#223]
Ref:https://secure.helpscout.net/conversation/1630295078/212856?folderId=2770543

1. upload the app icon and splash screen png in the required dimension in the Superpwa settings. However, when I download the  app apk, I see the app icon is replaced by the splash screen picture.

2. The App short name takes names only up to 15 characters and my app name is more than 15 characters.

Please resolve it ASAP.

**Comment by claraeonlearning** [comment]
Please resolve this issue ASAP. My work is in halt for this issue. 
I have taken a paid subscription of SUPERPWA and I have to run behind for these issues. Please solve this priority.

**Comment by syedimran22** [comment]
To implement this feature we need  Google PWA community update to load separate splash screen in APK.
Once we get those updates we will implement this feature
