### ISSUE TITLE
Splash Screens is not working on iPhone 13 Pro.

### ISSUE THREAD

**Issue by sanjaydadwani** [SuperPWA/Super-Progressive-Web-Apps#224]
Splash Screens is not working on iPhone 13 Pro due to different screen dimensions.

Ticket URL: https://secure.helpscout.net/conversation/1647261070/214296?folderId=4753923

**Comment by syedimran22** [comment]
As we have researched and tested with all the available resolutions for iPhone 13 but still splash screen is not rendering.

So once Apple provides any documentation regarding iPhone 13 Splash screen exact resolution we will implement it in our plugin.
