### ISSUE TITLE
Correction of user Interface at apk app generator  

### ISSUE THREAD

**Issue by VHGoradiya** [SuperPWA/Super-Progressive-Web-Apps#225]
On superpwa >> Android APK APP, the user interface at uploading a .keystore file shows tick mark and "upload new file" text. Only on clicking "upload new file" text, INPUT TYPE FILE tag is visible (refer screenshot.).

Screenshot before click - https://prnt.sc/1uz9hww
Screenshot after click - https://prnt.sc/1uzefn1

**Comment by syedimran22** [comment]
Committed in SuperPWA PRO: #98f76e7

**Comment by syedimran22** [comment]
Released in SuperPWA PRO Plugin of 1.12 Version
