### ISSUE TITLE
User is requesting to include feature :  progressing bar or preloading animation.

### ISSUE THREAD

**Issue by Marghoob123** [SuperPWA/Super-Progressive-Web-Apps#226]
Reference Ticket URL: https://secure.helpscout.net/conversation/1655127787/214909?folderId=5044124

User is requesting to include this feature : there is no progressing bar or preloading animation.
So that visitors of his website can wait for page loading.

**Comment by syedimran22** [comment]
Released in SuperPWA PRO Plugin of 1.11 Version
