### ISSUE TITLE
Need to add an option Where user can change iOS chrome notice message

### ISSUE THREAD

**Issue by ankit644** [SuperPWA/Super-Progressive-Web-Apps#236]
Ref:- https://secure.helpscout.net/conversation/1712961034/218931?folderId=4874234

Need to add an option Where user can change iOS chrome notice message

**Comment by syedimran22** [comment]
Committed in SuperPWA PRO: #3908721

**Comment by syedimran22** [comment]
Released in SuperPWA PRO Plugin of 1.12 Version
