### ISSUE TITLE
Encountering a warning in manifest regarding padding issues

### ISSUE THREAD

**Issue by Sasirekhamarella** [SuperPWA/Super-Progressive-Web-Apps#237]
Warning log: 
Declaring an icon with purpose: "any maskable" is discouraged. It is likely to look incorrect on some platforms due to too much or too little padding.

Reference ticket : https://wordpress.org/support/topic/error-when-auditiog-page-with-lighthouse/

**Comment by syedimran22** [comment]
Released in Version: 2.2
