### ISSUE TITLE
Conflict with XenForo 2.0

### ISSUE THREAD

**Issue by coolrecep** [SuperPWA/Super-Progressive-Web-Apps#24]
I think I can not merge posts or threads after installing SuperPWA on Worpdress.

https://xenforo.com/community/threads/thread-and-post-merge-in-xenforo-2-0.144776/

> What I am seeing is that the ajax request for inline moderation initially spawns two requests, XenForo and then superpwa. Afterwards all subsequent requests appear to be malformed with cached results.
> 
> I read about superpwa and the caching behavior seems consistent with how that software functions. Therefore I suspect interference by superpwa is causing this problem.
> 
> The frustrating thing is that I can't find where superpwa is coming from. The js file is in your web root but I can't see it anywhere in the page source or dom in XenForo.

**Comment by coolrecep** [comment]
Arun Hi,

It's happening on our forums: https://www.technopat.net/sosyal/

But to see the error, you need admin privileges. If you create an account, I'll provide the required credentials to test.

**Comment by coolrecep** [comment]
Done. You can do your testing here: https://www.technopat.net/sosyal/bolum/karargah.85/

Try to select topics to merge. And try to select posts inside topics to merge. The problem is, you can only select one topic. After selecting the second topic, the admin tool in the bottom is not updated.

**Comment by coolrecep** [comment]
![image](https://user-images.githubusercontent.com/13221472/39052830-8cb8e5b2-44ad-11e8-8fb1-cc588d0fc816.png)

This is how you select topics^^

**Comment by coolrecep** [comment]
Updated PWA to 1.5 and the issue persists.

**Comment by coolrecep** [comment]
Any update on that?

**Comment by coolrecep** [comment]
PWA 1.7 and the problem still exists.

**Comment by coolrecep** [comment]
Any update on that?

**Comment by arunbasillal** [comment]
Hello @coolrecep 

My apologies (sadly again) for the delay. We will find a resolution for this this weekend for sure. Its a priority for me.

**Comment by coolrecep** [comment]
![image](https://user-images.githubusercontent.com/13221472/39951363-d9c0952c-5591-11e8-8655-330b059d9d1d.png)

**Comment by coolrecep** [comment]
I'm available if you need any further collobration.

**Comment by coolrecep** [comment]
It will be a month tonight guys :/

**Comment by arunbasillal** [comment]
Hello @coolrecep That's sadly true :/

I was trying to replicate this by visiting: https://www.technopat.net/sosyal/bolum/karargah.85/
But I am not seeing the selection boxes and the menu. What did I miss? 

Sorry if I missed something because of my inability to read the language.

**Comment by coolrecep** [comment]
You can change the langugae from the bottom. I'm cehcking your permissions now.

**Comment by coolrecep** [comment]
You need to use the account you have created: superpwa. You do not seem to have logged in.

**Comment by arunbasillal** [comment]
I am logged in, but still not seeing anything similar to the image you have here: https://github.com/SuperPWA/Super-Progressive-Web-Apps/issues/24#issuecomment-383092160

But I see what might be happening here. This is completely outside of WordPress. 

Can you make a manual change in the service worker: https://www.technopat.net/superpwa-sw.js
Find `[/\/wp-admin/,/\/wp-login/,/preview=true/]` and change it to `[/\/wp-admin/,/\/wp-login/,/preview=true/,/\/sosyal/]`

This will exclude the forum from caching. Then on Chrome, uninstall the service worker, instructions here: https://github.com/SuperPWA/Super-Progressive-Web-Apps/issues/35#issuecomment-387161873

Please let me know how that goes.

**Comment by coolrecep** [comment]
Holy shiiiiiiiiit! Solved! Making more confirmations.

**Comment by arunbasillal** [comment]
Lol, it should because now the sw isn't doing much to the fetch request. (Although I have seen few cases where this is not 100% true and I am yet to figure out why.)

Assuming that this works, the manual edit will be replaced when you update SuperPWA the next time. I will probably add a filter and come up with a solution that works for you in the long term. 

Please let me know the results of your further tests.

**Comment by coolrecep** [comment]
OK. This was it! This solved 3 problems altogether:

- Multiple thread selection bug
- Multiple post selection bug
- [Thread edit bug!](https://xenforo.com/community/threads/editor-cache-bug.145349/)

**Comment by coolrecep** [comment]
OK, this one comes back. Even I delete SupwerPWA from Chrome apps, I get it back somehow...

https://xenforo.com/community/threads/editor-cache-bug.145349/

**Comment by arunbasillal** [comment]
Since you were able to replicate it with SuperPWA sw removed, its something else completely.

**Comment by coolrecep** [comment]
No, It is still SuperPWA. Turns out to be that I've to unregister from all of my browsers. But it is solved... I'll kepp you updated.

**Comment by coolrecep** [comment]
I need to unregister it every time. Could be related to cahce?

![image](https://user-images.githubusercontent.com/13221472/40009428-a705a6a2-57aa-11e8-972c-93a077bf6b86.png)

**Comment by coolrecep** [comment]
Nope. I still have to disable Service Worker every single time.

**Comment by coolrecep** [comment]
Still having this issue sometimes...

![image](https://user-images.githubusercontent.com/13221472/40912384-0c1b4466-67fa-11e8-84da-274e0bda1cdc.png)

**Comment by josevarghese** [comment]
Hello @coolrecep,

Good day! As from the screenshot that you shared I cannot notice any kind of issues or errors. Can you please let me know whether you mentioned about the links listed for **Clients**?

**Comment by coolrecep** [comment]
No, it's general. You need to read the entire thread.

**Comment by josevarghese** [comment]
I gone through the entire thread before replying, I can again confirm that there's no error or issue within the screenshot shared by you. If you visit any page within the scope and pages are opened within tabs - those links will be added into the **Clients**. Even if those are excluded from cache within the Service Worker. 

It's only an indication of the links the Service Worker considered as clients based on the scope of the manifest. The indication doesn't mean all those pages are cached for offline or Service Worker is working on all those links.

**Comment by coolrecep** [comment]
Nevermind, I've updated JS file again...

`[/\/wp-admin/,/\/wp-login/,/preview=true/,/\/sosyal/]`

**Comment by arunbasillal** [comment]
Hello @coolrecep 

I had introduced a filter in 1.8 to filter the never cache URLs. 

- [superpwa_sw_never_cache_urls](https://superpwa.com/codex/superpwa_sw_never_cache_urls/)

Please add this to the `functions.php` of your active theme:

```
/**
 * Exclude /sosyal/ from SuperPWA cache
 * 
 * @link https://superpwa.com/codex/superpwa_sw_never_cache_urls/
 */
function technopat_superpwa_exclude_sosyal_from_cache( $superpwa_sw_never_cache_urls ) {
	return $superpwa_sw_never_cache_urls . '/\/sosyal/';
}
add_filter( 'superpwa_sw_never_cache_urls', 'technopat_superpwa_exclude_sosyal_from_cache' );
```

This will ensure that `/sosyal` is excluded and will hold through the service worker updates.

**Comment by coolrecep** [comment]
Thanks. Did I paste it right?

![image](https://user-images.githubusercontent.com/13221472/40968143-7e072f90-68bd-11e8-82b6-d480ee6dabf1.png)

**Comment by arunbasillal** [comment]
It doesn't look right. Can you share the entire file via http://snippi.com. I will suggest where to paste it.

**Comment by coolrecep** [comment]
Here it is: http://snippi.com/s/r3625hk

**Comment by arunbasillal** [comment]
Thanks. 

Please remove the lines that you added and add it after the last line. i.e. after `//td_demo_state::update_state("magazine", 'full');`

This is how it will look like: http://snippi.com/s/p1ft3x4

**Comment by coolrecep** [comment]
Nope. Still. Does. Not. Work!

**Comment by arunbasillal** [comment]
If you check the current service worker: https://www.technopat.net/superpwa-sw.js?nocache you will notice that `\/sosyal/` is added to the `neverCacheUrls`

You might be seeing a cached version of the same.

**Comment by arunbasillal** [comment]
Just noticed a bug in the code snippet I sent you, forgot a comma. 

Here is the corrected one:

```
/**
 * Exclude /sosyal/ from SuperPWA cache
 * 
 * @link https://superpwa.com/codex/superpwa_sw_never_cache_urls/
 */
function technopat_superpwa_exclude_sosyal_from_cache( $superpwa_sw_never_cache_urls ) {
	return $superpwa_sw_never_cache_urls . ',/\/sosyal/';
}
add_filter( 'superpwa_sw_never_cache_urls', 'technopat_superpwa_exclude_sosyal_from_cache' );
```

Please replace the code in your functions.php and deactivate and reactivate SuperPWA so that the sw is regenerated.

**Comment by coolrecep** [comment]
Nope. Still the same.

**Comment by arunbasillal** [comment]
What do you mean? The sw is updated correctly now: https://www.technopat.net/superpwa-sw.js?nocache

Press Control/Command + F5 to clear the browser cache.

**Comment by coolrecep** [comment]
Nope. Does not work. The code we'he put inside the JS file was better though. But this method did not work.

**Comment by arunbasillal** [comment]
In the service worker, do you see this line?

`const neverCacheUrls = [/\/wp-admin/,/\/wp-login/,/preview=true/,/\/sosyal/];`

Isn't that the edit that you manually made? 

The code I gave you is supposed to add this to the service worker automatically so that you do not have to edit the service worker each time after you update the plugin. 

Are you saying that this isn't being added automatically now?

**Comment by coolrecep** [comment]
The first solution you've provided worked fine. This one:

Can you make a manual change in the service worker: https://www.technopat.net/superpwa-sw.js
Find [/\/wp-admin/,/\/wp-login/,/preview=true/] and change it to [/\/wp-admin/,/\/wp-login/,/preview=true/,/\/sosyal/]

But it was reverted back to default after the update.

> Are you saying that this isn't being added automatically now?

Yes.

**Comment by coolrecep** [comment]
Interesting that I have the code at the moment but still does not work...

`const neverCacheUrls = [/\/wp-admin/,/\/wp-login/,/preview=true/,/\/sosyal/];`

**Comment by coolrecep** [comment]
Cleared CloudFlare cache, still the same.

**Comment by arunbasillal** [comment]
Please see this, I see it on my browser just fine. 

![capture 1](https://user-images.githubusercontent.com/5751474/41147940-4c65c234-6b25-11e8-959f-1a0083119d18.png)

**Comment by coolrecep** [comment]
But it does not change the fact that I still can't select posts and SupwerPWA is still active.

![image](https://user-images.githubusercontent.com/13221472/41171455-511d23f6-6b59-11e8-927a-7a9e05812c2b.png)

**Comment by arunbasillal** [comment]
Was it working before when you had edited the service worker manually? If so, it might be because the service worker is not updated on the browser. 

The service worker will be installed and active on all pages of your domain, that's how service workers work. So you will see it on the application tab for your entire domain. 

If you check the console tab of dev tools while in the `/sosyal/` path and sub-path's do you see: `SuperPWA: Current request is excluded from cache.` in the console?

**Comment by coolrecep** [comment]
Yes. It says it's excluded and it works now.

- Updated LiteSpeed
- Cleared LiteSpeed Cache
- Cleared CLıudFlare cache

**Comment by arunbasillal** [comment]
Great. In all such matters for the future, remember to clear all the caches. 

Best regards.
