### ISSUE TITLE
Is there a way to make all posts and pages on wordpress offline?

### ISSUE THREAD

**Issue by alexmasita** [SuperPWA/Super-Progressive-Web-Apps#240]
I believe part of the idea of a progressive web application is to make all data that is accessible offline, easily and effortless available offline.  Is there a way, that I am currently unaware of, that allows the ability to cache all wordpress posts and pages with a single button click. 

The idea that I have to visit the page first before it is available to me offline seems counter intuitive in some instances especially when you know you extensively need to explore a fair big website.  

I have a client who is a mall with over 200 shops.  It would be great to enable the mall's regular customers to be able to click a single button on the client's website and have most or all of the pages on their device so they can freely browse the malls offerings while they are offline and having a coffee at one of the malls cafe or elsewhere with no connection before they visit the mall.

I have this challenge myself in most cases where I am able to access the mall's website at home because I have good internet connection, but once at the mall where I want to select the shops to visit, I cannot use my phones data because the signal is poor within the mall.  But since am a regular at the mall, I really would not mind cacheing all of the malls pages on my device at home in advance.  

This would still be a far better solution, I guess, with less storage needs than installing a full fledged android application that would also aim to solve this problem but with more storage needs.

**Comment by syedimran22** [comment]
Hi @alexmasita 

We have already implemented a feature that is similar to your requirement which is  Precaching in that you can select the Automatic Precaching Option.

And regarding how to implement it you can go through this documentation https://superpwa.com/doc/how-to-setup-precaching-in-superpwa/#automatic-precaching

**Comment by alexmasita** [comment]
This is super great.  I have just bought the pro version of the plugin, installed it and activated.  On the plugins page, it appears to be correctly installed with a link to a page that should allow the entry of the licence key.  However, when I click it, it redirects to the main dashboard.  On checking the dashboard menus, the "Super PWA" menu is no where to be seen even under the "settings" dashboard menu.  I have tried uninstalling and reinstalling the plugin to no avail.  Am I missing something?

I have submitted a request for help on your contact page with the url and credentials for the back end here: [https://superpwa.com/contact/](https://superpwa.com/contact/).  Let me know if you need any further information.
