### ISSUE TITLE
Add to Home Screen Pop up is not working

### ISSUE THREAD

**Issue by supriyavr** [SuperPWA/Super-Progressive-Web-Apps#241]
I installed and set up the plugin for my woocommerce website. But it is not working. I am not getting 'Add to Home Screen' pop up

**Comment by syedimran22** [comment]
Hi @supriyavr 

Could you please contact our support team using this URL https://superpwa.com/contact/ or from our plugin forum.

As our Support team will go through your issue thoroughly and try to fix it there itself
