### ISSUE TITLE
Need to add the Navigation Bar feature in SuperPWA

### ISSUE THREAD

**Issue by kupveja** [SuperPWA/Super-Progressive-Web-Apps#243]
Need to add the Navigation Bar feature in SuperPWA
ref - https://prnt.sc/26cs2ir
ticket link - https://secure.helpscout.net/conversation/1753154830/222087?folderId=4459751#modal

**Comment by Sanjeevsetu** [comment]
Navigation Bar in SuperPWA is now live in superPWA Pro version.
