### ISSUE TITLE
Works with iOS/Safari 

### ISSUE THREAD

**Issue by c9obvi** [SuperPWA/Super-Progressive-Web-Apps#25]
Works if know to manually add it to the home screen. URL bar is gone the chosen pages are cached. As I noticed you addressed adding more pages already. Although some stuff works;
~1. the icon was a screenshot of the current page (EDIT) got it to work.
2. "App" name was displayed correctly from the "Short name" input in settings.
3.  was not promoted with instructions to "download" or add to home screen. But I could write a manual alert pop up with instructions no worries there. However, now that I think about it that means users that do get the pop up would be getting two pop-ups if I added one for iOS users myself...

Looking forward to response! Thank you!

**Comment by c9obvi** [comment]
second update:
- **iOS** has no splash screen either. successfully caches and eliminated the URL bar and nav bar from browsers.

-no pop up on chrome or firefox browser for **android** phone (OnePlus 3)

**Comment by josevarghese** [comment]
Hello @c9obvi ,

Good day and thanks for using our plugin **Super Progressive Web Apps**.

As regarding the iOS, I would like to mention that PWA is not at all fully supporting upon iOS devices or Safari. You can read more about it at : [here](https://medium.com/@firt/progressive-web-apps-on-ios-are-here-d00430dee3a7)

Currently iOS, just started supporting from the latest version 11.3 which released 3 weeks back  (ie; it's not supporting splash screens, Add to HomeScreen prompt, icon, background color, Theme color and some of features of the PWA). So hopefully we can expect that they will support the rest features of PWA in coming updates.
 
 
 
> no pop up on chrome or firefox browser for android phone (OnePlus 3)

Can you please let me know the browser version of Chrome and Firefox? 
 
 
 

Looking forward.

Regards,
Jose Varghese

**Comment by c9obvi** [comment]
Makes sense on the iOS parts. I look forward to you guys being the standard and covering all browsers and major devices. 

- load up is a little slow as well. Both devices.

- Actually the fact that it isnt popping up on the android allowed me to use my own pop up instructing people how to "add to home screen" so now through wordpress pop up its appearing regardless of browser of device. 

- To answer your question. The android device running chrome and Firefox are the latest versions available in the Google Plat store. I would like to add that the Firefox browser does **not** have a "add to home screen" button in any tab or menu where is usually found in other mobile browsers (including iOS)

- Currently testing out using buddypress just to see how dynamic it would feel. I will be trying a more e-commerce style next.

Thanks for prompt response by the way!! I hope I have been detailed enough.

**Comment by josevarghese** [comment]
Hello @c9obvi 

Can you please share your website URL so that I can test upon my devices and can update you more on it.

Thanks!

**Comment by c9obvi** [comment]
yes, (please keep in mind this is an experiment url not a finished idea xD)
https://privi.club

**Comment by josevarghese** [comment]
Thanks for sharing the URL.

 I just checked your website and noticed that one image file upon your website is not loading as secured (ie; not https://). Even though SSL certificate is installed, the page doesn’t show a green padlock upon browser, because not all links in the source are **`https://`**

As for progressive web apps, the website should be served fully via https://, then only the **Add to homescreen** prompt will occur.

The image which is loading on **`http://`** is the favicon which you added. ie; This image http://privi.club/wp-content/uploads/2018/03/privi-favicon-2.png

Can you please re upload that image again to the favicon or add https:// into the URL of favicon.

Looking forward.

Thanks,
Jose Varghese
**[SuperPWA](https://superpwa.com)**

**Comment by c9obvi** [comment]
It does say https on my end hm

![https favicon bug](https://user-images.githubusercontent.com/31329416/38825131-5764b224-4160-11e8-8b6d-31082dc9e87e.jpg)

I will sift through all files for any remaining http and will update

Thanks

**Comment by josevarghese** [comment]
Hello @c9obvi ,

I mentioned to change https:// upon from where you added image to the favicon.  I think you added the favicon image via either theme settings or otherwise via Appearance > Customize. Isn't it? Can you select the image again from there?

Looking forward.

Thanks,
Jose Varghese

**Comment by c9obvi** [comment]
Yeah thats a screenshot of me replacing the icon in the said settings you explain above. I select the one that is https as you see in screen shot. Publish but remains SSL broken. I will contact hosting provider.

**Comment by josevarghese** [comment]
hello @c9obvi Any updates?

**Comment by josevarghese** [comment]
Hello @c9obvi 

I checked your website now and noticed that the website is still not secure (ie; not https://), as I mentioned earlier our plugin only works upon secured websites that shows green padlock on browser. 

As you haven't changed your website into secure (**ie; https://**) and this is something you need to fix upon your site's end. I'm closing this issue, if you have any other issues please don't hesitate to let us know!

Thanks!

**Comment by veysek34** [comment]
I discovered the superwpa plugin for [my website](https://optimumwelt.de). but i can't get results on iphone ios devices. Conforms to all policies.
