### ISSUE TITLE
Need to add a feature to set-timing for showing CTA installing banner

### ISSUE THREAD

**Issue by 77naveenop** [SuperPWA/Super-Progressive-Web-Apps#250]
There is a user's requirement to add a feature in CTA for set-timing for showing Add To Home Screen banner on screen when someone visits the website and once the ticket is built please review the UX with Ahmed Sir.

reference help scout URL -: https://secure.helpscout.net/conversation/1791636100/227706?folderId=5893230

**Comment by syedimran22** [comment]
Committed in SuperPWA PRO : #cfc0a88

**Comment by syedimran22** [comment]
Released in SuperPWA PRO of Version: 1.15
