### ISSUE TITLE
SuperPwa not working in Firefox

### ISSUE THREAD

**Issue by Sdaud1950** [SuperPWA/Super-Progressive-Web-Apps#253]
SuperPWA installation feature not showing in firefox browser.

Reference Helpscout URL-: https://secure.helpscout.net/conversation/1778263691/226556?folderId=6370795

Reference video -

https://monosnap.com/file/glaGWXNHWsEdAPHAxDfQdwS6hgT0XQ

**Comment by syedimran22** [comment]
As of now firefox browser does not support PWA feature in their browser

https://9to5google.com/2021/01/27/firefox-discontinues-work-pwa-desktop/
