### ISSUE TITLE
Need to add Automatic precaching support for custom post 

### ISSUE THREAD

**Issue by MohammedAkramU7** [SuperPWA/Super-Progressive-Web-Apps#261]
Helpscout URL:-
https://secure.helpscout.net/conversation/1816300364/231080?folderId=5893563

Description:-
Need to add automatic precaching functionality in custom post.

**Comment by Sanjeevsetu** [comment]
We already have this feature. follow the doc link https://superpwa.com/docs/article/how-to-setup-precaching-in-superpwa/.
