### ISSUE TITLE
Need to change superPWA setting's UI 

### ISSUE THREAD

**Issue by 77naveenop** [SuperPWA/Super-Progressive-Web-Apps#263]
There is an option named "Show Only In PWA" when we enable this, the loader should be shown only in PWA but if we enable another option "Loader Display On" mobile or desktop, it also shows there.  

I think  "Show Only In PWA" should be renamed as "Show in PWA"

Reference helpscout URL -: https://secure.helpscout.net/conversation/1820621815/231835?folderId=5893230

Reference screenshot -: https://prnt.sc/YexzzoRw2DWG

**Comment by ajithkumar072** [comment]
Released in SuperPWA Pro Version : 1.19
