### ISSUE TITLE
Need to add functionality banner show on specific pages

### ISSUE THREAD

**Issue by MohammedAkramU7** [SuperPWA/Super-Progressive-Web-Apps#266]
HelpScout:-
https://secure.helpscout.net/conversation/1829104628/234059?folderId=5893563

Description:-
User want banner only shown on the home page or other specific pages.

**Comment by Sanjeevsetu** [comment]
We have added new add-on called 'Visibility' in pro version. just check it. Link: https://superpwa.com/freevspro/
