### ISSUE TITLE
Menu button not displaying in SuperPWA mobile app.

### ISSUE THREAD

**Issue by DeheemB** [SuperPWA/Super-Progressive-Web-Apps#270]
Ref link: https://secure.helpscout.net/conversation/1816113540/231030?folderId=6406114
Ref Screenshot Website: https://prnt.sc/qYhYt5c-g4hS
Ref Screenshot SuperPWA : https://prnt.sc/-8OYJQQrhx3l

**Comment by syedimran22** [comment]
User was using Custom CSS due to which this issue was occuring 
screenshot : https://www.awesomescreenshot.com/image/26023435?key=ce533899820dafd4f58a11a3a5a6b54d
