### ISSUE TITLE
Need to load superpwa manifest ahead of theme's manifest

### ISSUE THREAD

**Issue by syedimran22** [SuperPWA/Super-Progressive-Web-Apps#271]
Desc:  Add to homescreen is not working as theme's manifest is loading prior to superpwa manifest
ref: https://secure.helpscout.net/conversation/1849362935/237647?folderId=4741024

**Comment by sajandara** [comment]
https://secure.helpscout.net/conversation/1838508275/235665?folderId=1060556

Same issue.

**Comment by syedimran22** [comment]
Released in SuperPWA Version: 2.2.5
