### ISSUE TITLE
Need to add functionality Navigation Bar in SuperPWA

### ISSUE THREAD

**Issue by DeheemB** [SuperPWA/Super-Progressive-Web-Apps#273]
Ticket: https://secure.helpscout.net/conversation/1816113540/231030?folderId=1060556
User want to have a navigation bar at the bottom of the SuperPWA app. Same as in PWAforWP.

The output should be: https://prnt.sc/5FhIsragFtOi

**Comment by Sanjeevsetu** [comment]
Navigation Bar in SuperPWA is now live in superPWA Pro version.
