### ISSUE TITLE
Need to Fix the BUG of Show CTA Only on iOS Device features.

### ISSUE THREAD

**Issue by Sdaud1950** [SuperPWA/Super-Progressive-Web-Apps#275]
When  Show CTA Only on iOS Device features is ON then native Add to Home screen should be displayed on android device.
REF:https://secure.helpscout.net/conversation/1817279539/231263?folderId=6370795

**Comment by sajandara** [comment]
Same issue

https://secure.helpscout.net/conversation/1860751013

**Comment by syedimran22** [comment]
SuperPWA PRO Commit : #b06434f

**Comment by ajithkumar072** [comment]
Released in SuperPWA Pro Version : 1.19
