### ISSUE TITLE
Serviceworker cache the videos on the website and it stops them from playing.

### ISSUE THREAD

**Issue by sajandara** [SuperPWA/Super-Progressive-Web-Apps#278]
The serviceworker caches the videos on the user's website and stops them from playing until it is fully downloaded also, there is a warning in the console "current request is excluded from cache" but no URL is declared to be excluded.

Reference Ticket: https://secure.helpscout.net/conversation/1864315810/239892?folderId=6406109.

**Comment by syedimran22** [comment]
Commit : https://github.com/SuperPWA/Super-Progressive-Web-Apps/commit/d082caa30f8ee316d45ec2efdb870b0751e39e90

**Comment by ajithkumar072** [comment]
Released in SuperPWA Pro Version : 1.19
