### ISSUE TITLE
Script does not have a MIME type.

### ISSUE THREAD

**Issue by Sdaud1950** [SuperPWA/Super-Progressive-Web-Apps#280]
Ref:https://secure.helpscout.net/conversation/1858729676/239153?folderId=6370795

When Wp Fastest Cache is enabled, the script does not have a MIME-type error.

Ref Screenshot:https://prnt.sc/YUlmvuXkSH6_

**Comment by DeheemB** [comment]
Another user: https://magazine3.in/conversation/4566?folder_id=13

When Wp Fastest Cache is enabled, the add to home screen is not working in Windows/Android.

**Comment by darkstudio** [comment]
Any news ? We are stuck since many month.
Regards,

**Comment by darkstudio** [comment]
Have you fix this issue ??

**Comment by MohammedAkramU7** [comment]
Another user:- https://magazine3.in/conversation/8037?folder_id=21

When Wp Fastest Cache is enabled, the script does not have a MIME-type error

Ref screenshot:- https://monosnap.com/direct/QhVH6kWaItyh30oWUimPjAWMfOeeQz

**Comment by darkstudio** [comment]
hi,

Same issue on another client website, the problem growing...

**Comment by akshaywali** [comment]
Update pushed in SuperPWA 2.2.11
