### ISSUE TITLE
Need to change the installation steps while QR code is scanned using Safari.

### ISSUE THREAD

**Issue by DeheemB** [SuperPWA/Super-Progressive-Web-Apps#281]
Ticket: https://magazine3.in/conversation/4585?folder_id=13

Issue: https://prnt.sc/CHRFLvmw_xRB

**Comment by syedimran22** [comment]
SuperPWA PRO Commit : #5e78d9a

**Comment by ajithkumar072** [comment]
Released in SuperPWA Pro Version : 1.19
