### ISSUE TITLE
Add to home screen banner("CTA") in IOS chrome is not showing the steps How to install CTA.

### ISSUE THREAD

**Issue by Sdaud1950** [SuperPWA/Super-Progressive-Web-Apps#283]
In IOS chrome when we try to click on Add to home screen banner then no steps are showing **How to install CTA.**
Ref:https://magazine3.in/conversation/4604?folder_id=29

**Comment by syedimran22** [comment]
SuperPWA PRO Commit : #5e78d9a

**Comment by ajithkumar072** [comment]
Released in SuperPWA Pro Version : 1.19
