### ISSUE TITLE
Need to change the URL for Enter License key from plugins area 

### ISSUE THREAD

**Issue by syedimran22** [SuperPWA/Super-Progressive-Web-Apps#286]
Desc:  Need to change the URL for Enter license key button as it is redirecting to a page that is reflecting Sorry, you are not allowed to access this page.

Screenshot: https://ibb.co/TgFZB8c
https://ibb.co/CvpgLFb

**Comment by ajithkumar072** [comment]
Released in SuperPWA Pro Version : 1.19
