### ISSUE TITLE
Splash Screen Icon is taking app icon image

### ISSUE THREAD

**Issue by Sdaud1950** [SuperPWA/Super-Progressive-Web-Apps#290]
When we are uploading Splash Screen Icon the quality of the image is not proper because it's capturing the AppIcon image due to which the image is blur
REF: https://magazine3.in/conversation/4667?folder_id=29

**Comment by akshaywali** [comment]
For android is not currently possible to have different App icon and screenshot icon , they will be the same as app icon.
For IOS there can be different icons for app icon and screenshot

**Comment by akshaywali** [comment]
Update pushed in SuperPWA 2.2.11
