### ISSUE TITLE
Need to add new functionality "data can be Download from data analytics"

### ISSUE THREAD

**Issue by Sdaud1950** [SuperPWA/Super-Progressive-Web-Apps#291]
A user should be able to download data from the addon data analytics.

Ref ticket: https://magazine3.in/conversation/4726?folder_id=29

**Comment by kumawatvikas** [comment]
Ref:- https://github.com/SuperPWA/super-progressive-web-apps-pro/commit/c972c70eb3973c5d86b148f4d1438abd7abb4196
