### ISSUE TITLE
In IOS Safari CTA when we click on closing button the second pop-up appears. 

### ISSUE THREAD

**Issue by Sdaud1950** [SuperPWA/Super-Progressive-Web-Apps#292]
When we click the close button on the first iOS Safari CTA pop-up, the second one arrives. It should not arrive.

Ref Video:https://www.awesomescreenshot.com/video/9084362?key=21d41f95f41c8d789246117d462dfe34

Ref helpscout:https://secure.helpscout.net/conversation/1817279539/231263?folderId=6370795

**Comment by akshaywali** [comment]
Issue Fixed in SuperPWA PRO 1.20 version
