### ISSUE TITLE
Need to add a new functionality for IOS CTA where step should show how to install CTA in Opera/firefox/Microsoft Edge 

### ISSUE THREAD

**Issue by Sdaud1950** [SuperPWA/Super-Progressive-Web-Apps#293]
Need to add new functionality for IOS CTA where step should show how to install CTA in Opera/firefox/Microsoft Edge.

Ref:https://secure.helpscout.net/conversation/1817279539/231263?folderId=6370795

**Comment by Sanjeevsetu** [comment]
This feature is now available in pro extension. Just upgrade to it. https://superpwa.com/freevspro/
