### ISSUE TITLE
Exclude URLs from Cache list option is not working properly.

### ISSUE THREAD

**Issue by MohammedAkramU7** [SuperPWA/Super-Progressive-Web-Apps#300]
Freescout:-https://magazine3.in/conversation/27728?folder_id=4

Description:-
When a user excludes URLs but keeps the cached URLs

**Comment by otgooneo** [comment]
Still waiting it to be fixed. Purchased paid plugin but couldn`t use it because of this bug.

**Comment by akshaywali** [comment]
Check that if your hosting/ plugin is generating dynamic cache ,  you have to clear dynamic cache after Exclude URL update. If you still find any issue contact our support.

**Comment by otgooneo** [comment]
Disabled all dynamic and static caches on the server and checked it again, but issue is still there.

**Comment by pradipshende** [comment]
Push changes in Super Progressive Web Apps 2.2.7 version
