### ISSUE TITLE
Splash icon takeover the application icon

### ISSUE THREAD

**Issue by MohammedAkramU7** [SuperPWA/Super-Progressive-Web-Apps#302]
Freescout:-
https://magazine3.in/conversation/12609?folder_id=21

Description:-
when user download the superpwa  app app icon and  splash  screen icon both should be same

Issue screenshot
https://prnt.sc/SliX3P31LLwV
https://prnt.sc/xMbHAbUwZ6t_

**Comment by MohammedAkramU7** [comment]
This user is facing the same issue:  https://magazine3.in/conversation/28829?folder_id=39

**Comment by akshaywali** [comment]
For android is not currently possible to have different App icon and screenshot icon , they will be the same as app icon.
For IOS there can be different icons for app icon and screenshot

**Comment by akshaywali** [comment]
Update pushed in SuperPWA 2.2.11
