### ISSUE TITLE
IOS welcome screen showing blank/white page.

### ISSUE THREAD

**Issue by sajandara** [SuperPWA/Super-Progressive-Web-Apps#307]
IOS welcome screen showing blank/white space even after setting up the Apple Touch Icons & Splash Screen.

Ref ticket: https://magazine3.in/conversation/19217?folder_id=27

Ref video: https://monosnap.com/direct/P7LW5aVIDuS8d3zfd2kdLZB9GeJQsK

**Comment by akshaywali** [comment]
This issue is duplicate of  ticket https://github.com/SuperPWA/Super-Progressive-Web-Apps/issues/343 IOS splashcreen Icon not working
