### ISSUE TITLE
CTA shortcode feature not working in IOS

### ISSUE THREAD

**Issue by MohammedAkramU7** [SuperPWA/Super-Progressive-Web-Apps#308]
Freescout:- https://magazine3.in/conversation/20263?folder_id=21

Description:-
The CTA shortcode feature works perfectly in Android but not in IOS. 

Issue screenshot
https://prnt.sc/5YSQ4D6etXKL

**Comment by akshaywali** [comment]
![iPhone XR_15 5](https://user-images.githubusercontent.com/36995680/181753377-a6383587-c2c8-4a73-be78-0e3d4a7b5203.png)

Shortcode is working fine on IOS and Android on Pro version
