### ISSUE TITLE
APK is not generating

### ISSUE THREAD

**Issue by MohammedAkramU7** [SuperPWA/Super-Progressive-Web-Apps#309]
Freescout:- https://magazine3.in/conversation/22616?folder_id=21

Description:-
When the user tries to generate the APK error shows "APK not created try later ErrorDetails"

Issue screenshot:-
https://prnt.sc/DitDX-Cx4qJS

**Comment by 77naveenop** [comment]
New users with the same issue -: https://magazine3.in/conversation/23894?folder_id=23, https://magazine3.in/conversation/23843?folder_id=23

**Comment by Sdaud1950** [comment]
Another user with the same issue.
https://magazine3.in/conversation/23843?folder_id=29

**Comment by akshaywali** [comment]
Released in SuperPWA PRO 1.20 version
