### ISSUE TITLE
getting error when we are adding range data in cache

### ISSUE THREAD

**Issue by MohammedAkramU7** [SuperPWA/Super-Progressive-Web-Apps#311]
Freescout:-https://magazine3.in/conversation/22526?folder_id=21

Description:-
The user adds the video in web stories and gets errors in the console.

Error:-
superpwa-sw.js:119 Uncaught (in promise) TypeError: Failed to execute 'put' on 'Cache': Partial response (status code 206) is unsupported at superpwa-sw.js:119:14

Error screenshot:-
https://prnt.sc/MMbLg7v41Zwe

**Comment by pradipshende** [comment]
Push changes in Super Progressive Web Apps 2.2.7 version
