### ISSUE TITLE
While testing the SupwerPwa on https://www.pwabuilder.com/tool, the service for offline shows zero scores.

### ISSUE THREAD

**Issue by Sdaud1950** [SuperPWA/Super-Progressive-Web-Apps#316]
While testing the SuperPwa on the https://www.pwabuilder.com/ tool the Service Worker score is showing zero for Works Offline and some Recommended for the Manifest are also showing zero.  Need to improve the scores of the offline service workers and Manifest.

*While testing on the  https://www.pwabuilder.com/ tool all the Recommended should be in green.*

Ref screenshot for the SuperPwa manifest: https://prnt.sc/ppNnYEJzP_Rb 
Ref screenshot for the SuperPwa offline services worker: https://prnt.sc/9tMtNj8tb8VB 

Ref fresscoput: https://magazine3.in/conversation/33771?folder_id=29

**Comment by pradipshende** [comment]
Push changes in Super Progressive Web Apps 2.2.8 version
