### ISSUE TITLE
Not able to upload the APK App.

### ISSUE THREAD

**Issue by Sdaud1950** [SuperPWA/Super-Progressive-Web-Apps#318]
While uploading the Apk app to the Google Play console, there is an error "Your application is currently targeting API level 30. However, it should target at least API level 31 in order to rely on the latest optimized APIs for increased security and improved performance. Change your app's target API level to target at least level 31"

Ref Screenshot. https://prnt.sc/pLX_xIbFGDIZ 
Ref ticket:https://magazine3.in/conversation/33952?folder_id=29

**Comment by kupveja** [comment]
one more user is getting  the same issue.
ref - https://magazine3.in/conversation/29434?folder_id=15

**Comment by pradipshende** [comment]
Issue fixed in Node (Server) site
