### ISSUE TITLE
Need to provide support for deep linking from the web to PWA.

### ISSUE THREAD

**Issue by Sdaud1950** [SuperPWA/Super-Progressive-Web-Apps#320]
When a user sends the URL link of THE website through the SMS then the Link should open in the iPhone/Android home PWA and not the Safari/chrome browser. 

Ref.sources
[Deep linking from Web to PWA (Standalone Version)]
https://stackoverflow.com/questions/45979191/deep-linking-from-web-to-pwa-standalone-version 

Ref free scout. https://magazine3.in/conversation/37242?folder_id=29

**Comment by Sanjeevsetu** [comment]
Related https://github.com/SuperPWA/Super-Progressive-Web-Apps/issues/277
