### ISSUE TITLE
CTA is not working properly in IOS

### ISSUE THREAD

**Issue by MohammedAkramU7** [SuperPWA/Super-Progressive-Web-Apps#321]
Freescout:-https://magazine3.in/conversation/30444?folder_id=21

Description:-
CTA appears after the app is installed, and CTA appears inside the app. 

Issue screenshot:-
https://prnt.sc/quTlFZDy3XCy

**Comment by MohammedAkramU7** [comment]
Another user facing same issue https://magazine3.in/conversation/51597?folder_id=21

**Comment by pradipshende** [comment]
Push changes in Super Progressive Web Apps PRO 1.22 version
