### ISSUE TITLE
APKs are not working on the Android V.12

### ISSUE THREAD

**Issue by sajandara** [SuperPWA/Super-Progressive-Web-Apps#322]
APKs are not working on Android V.12 and showing a warning "Has a bug"

Reference screenshot: https://prnt.sc/1TepTetGRTuJ https://prnt.sc/yHG-BNMzGG7A

Reference ticket: https://magazine3.in/conversation/47782?folder_id=27

**Comment by kupveja** [comment]
One more user also getting this issue - https://magazine3.in/conversation/29434?folder_id=15

**Comment by aosoeawe** [comment]
It's really not understandable that a PWA app is not compatible with the most popular version of android. 
Seriously, I think most of the people buy PRO for the apk generating feature, but the essential function is fatal.
I think Super PWA should show us any of the progresses for making it compatible with ver 12, and tell us when it will be successfully developed, and why it is not working in ver 12.

**Comment by pradipshende** [comment]
We have fixed the issue in our server

**Comment by pradipshende** [comment]
we have fixed the issue in our server

**Comment by aosoeawe** [comment]
APK not created try later.
ErrorDetails: Error generating app package: Request path contains unescaped characters code: ERR_UNESCAPED_CHARACTERS stack: TypeError: Request path contains unescaped characters at new NodeError (node:internal/errors:393:5) at new ClientRequest (node:_http_client:182:13) at request (node:https:360:10) at /srv/updated-app-builder/node_modules/node-fetch/lib/index.js:1438:15 at new Promise () at Function.fetch [as default] (/srv/updated-app-builder/node_modules/node-fetch/lib/index.js:1407:9) at FetchUtils.fetch (/srv/updated-app-builder/node_modules/@bubblewrap/core/dist/lib/FetchUtils.js:35:46) at ImageHelper.fetchIcon (/srv/updated-app-builder/node_modules/@bubblewrap/core/dist/lib/ImageHelper.js:93:56) at TwaGenerator.generateIcons (/srv/updated-app-builder/node_modules/@bubblewrap/core/dist/lib/TwaGenerator.js:210:45) at TwaGenerator.createTwaProject (/srv/updated-app-builder/node_modules/@bubblewrap/core/dist/lib/TwaGenerator.js:331:24)

This is the error that is occuring.
I think it's not fixed normally.
