### ISSUE TITLE
CTA is not working in RTL

### ISSUE THREAD

**Issue by ahmedkaludi** [SuperPWA/Super-Progressive-Web-Apps#323]

**Comment by akshaywali** [comment]
Unable to  recreate issue , CTA is working fine in RTL , there were little alignment issue  that are fixed in SuperPWA PRO.

**Comment by akshaywali** [comment]
![image](https://user-images.githubusercontent.com/36995680/216286318-d77f8462-7a72-4d1d-b2aa-47708026e250.png)
**Make sure proper text direction setting is selected.**
