### ISSUE TITLE
Errors "unable to verify the first certificate" appears when generating the APK 

### ISSUE THREAD

**Issue by MohammedAkramU7** [SuperPWA/Super-Progressive-Web-Apps#327]
Ref ticket:- https://magazine3.in/conversation/52091?folder_id=21

**Comment by akshaywali** [comment]
This issue arises when when the  website ssl certificate is not trusted.
![image](https://user-images.githubusercontent.com/36995680/209554882-76bfe47d-3172-4197-8068-072f65111173.png)
