### ISSUE TITLE
 Need to create an option where users can add posts as start pages.

### ISSUE THREAD

**Issue by Sdaud1950** [SuperPWA/Super-Progressive-Web-Apps#328]
Need to create an option where users can add posts as a start page. 
Right now, we have the option of adding the start page only.

 Ref screenshot.https://prnt.sc/_1SEYOYe7NFn 

Ref help scout. https://magazine3.in/conversation/52688?folder_id=29

**Comment by akshaywali** [comment]
pushed in SuperPWA 2.2.15
