### ISSUE TITLE
The Call to Action banner is still showing after the installation of SuperPWA.

### ISSUE THREAD

**Issue by Sdaud1950** [SuperPWA/Super-Progressive-Web-Apps#330]
The Call to Action banner is still showing after the installation of SuperPWA.

Ref video. https://monosnap.com/direct/kp8Q45hhNJpHBWQySI0dLY5Y92QKfu 

Ref ticket. https://magazine3.in/conversation/55354?folder_id=29

**Comment by sajandara** [comment]
The same issue is faced by another user.
https://magazine3.in/conversation/66066?folder_id=27

**Comment by Sdaud1950** [comment]
same issue with this user: https://magazine3.in/conversation/83556?folder_id=29

**Comment by akshaywali** [comment]
Code updated at SuperPWA PRO 1.24  https://github.com/SuperPWA/super-progressive-web-apps-pro/commit/9e8f164254cc8224df79cfeb49e545a47d814a9d
