### ISSUE TITLE
APK Generator Compatible with 10, 11 / Not with 12

### ISSUE THREAD

**Issue by aosoeawe** [SuperPWA/Super-Progressive-Web-Apps#335]
This should really be noticed to everyone who is trying to buy PRO feature of SuperPWA.
If this is not compatible with 12, it means that any of the recent devices can't use an app that is made by SuperPWA APK generator. 
1 year have been passed since android 12 is out in the public. This fatal issue is most important for this service to be maintained.

**Comment by akshaywali** [comment]
We have updated our APK generation library. So this is issue is already fixed as of NOV 7 2022 .
