### ISSUE TITLE
Getting warning in error.log

### ISSUE THREAD

**Issue by MohammedAkramU7** [SuperPWA/Super-Progressive-Web-Apps#337]
Ref ticket:- https://magazine3.in/conversation/60236?folder_id=21

Error:-
Undefined variable $reset_cookies in /home/rvwheelator/app.rvwheelator.com/wp-content/plugins/super-progressive-web-apps-pro/addons/pre-loader.php on line 411

**Comment by akshaywali** [comment]
Update pushed in SuperPWA PRO 1.22
