### ISSUE TITLE
Error appear in Google Search Console

### ISSUE THREAD

**Issue by MohammedAkramU7** [SuperPWA/Super-Progressive-Web-Apps#340]
Ref:- https://magazine3.in/conversation/61146?folder_id=21

Description:-
When the user tests the URL in the Google Search Console, an error appears.

Issue URL:-
https://prnt.sc/9Bcx-0H31xZv
https://prnt.sc/19gUxIF2zCGo

**Comment by DARKNET-TOOL** [comment]
> Ref:- https://magazine3.in/conversation/61146?folder_id=21
> 
> 
> 
> Description:-
> 
> When the user tests the URL in the Google Search Console, an error appears.
> 
> 
> 
> Issue URL:-
> 
> https://prnt.sc/9Bcx-0H31xZv
> 
> https://prnt.sc/19gUxIF2zCGo

Are you facing the problem and need someone who can resolve this for you Humm?

**Comment by akshaywali** [comment]
Issue is user specific and user is not providing access. So closing this ticket.
