### ISSUE TITLE
Warning "Undefined array key "excluded_urls"" appearing on the website.

### ISSUE THREAD

**Issue by sajandara** [SuperPWA/Super-Progressive-Web-Apps#341]
Warning "Undefined array key "excluded_urls" appearing on the website.

Ref ticket: https://magazine3.in/conversation/65807?folder_id=27

**Comment by Sasirekhamarella** [comment]
Same issue: https://wordpress.org/support/topic/php-warning-384/

**Comment by akshaywali** [comment]
Issue is fixed in 2.2.8 update . Please inform the users and check if it is working for them .

**Comment by akshaywali** [comment]
Closing the issue for now , if any user faces this issue reopen or create a new ticket
