### ISSUE TITLE
In iOS, the splash screen icon does not work. 

### ISSUE THREAD

**Issue by Sdaud1950** [SuperPWA/Super-Progressive-Web-Apps#343]
In iOS, the splash screen icon does not work. 

Ref video.https://monosnap.com/direct/X3i2qxk09U6zpD9Q4M5XakpxigIbRA 

Ref ticket. https://magazine3.in/conversation/66399?folder_id=29 

NOTE: **The IOS splash screen icon works on iPhone 11 and lower but not on devices higher than the iPhone 11.** 

https://prnt.sc/siCMDmtD7fyQ Size of the splash screen icon is showing bigger.

**Comment by akshaywali** [comment]
pushed in  2.2.9
