### ISSUE TITLE
Escaping is missing

### ISSUE THREAD

**Issue by Sanjeevsetu** [SuperPWA/Super-Progressive-Web-Apps#348]
Check these files:

D:\XAMPP\htdocs\magazine3\wp-content\plugins\Super-Progressive-Web-Apps\admin\admin-ui-render-settings.php
D:\XAMPP\htdocs\magazine3\wp-content\plugins\Super-Progressive-Web-Apps\admin\admin-ui-render-upgrade.php
D:\XAMPP\htdocs\magazine3\wp-content\plugins\Super-Progressive-Web-Apps\functions\common.php

**Comment by akshaywali** [comment]
pushed in  2.2.9
