### ISSUE TITLE
Security nonce is missing

### ISSUE THREAD

**Issue by Sanjeevsetu** [SuperPWA/Super-Progressive-Web-Apps#349]
For add_action( 'wp_ajax_superpwa_send_feedback', 'superpwa_send_feedback' ) in D:\XAMPP\htdocs\magazine3\wp-content\plugins\Super-Progressive-Web-Apps\admin\mb-helper-function.php

and remove blank new line from the file

**Comment by akshaywali** [comment]
pushed in  2.2.9
