### ISSUE TITLE
How to Unisntall Completely?

### ISSUE THREAD

**Issue by coolrecep** [SuperPWA/Super-Progressive-Web-Apps#35]
Where is that file? How come it still loads?

![image](https://user-images.githubusercontent.com/13221472/39693802-f3e76ba8-51ed-11e8-8d60-c739dfada0d7.png)

**Comment by arunbasillal** [comment]
Hello @coolrecep 

I noticed that you were quite frustrated earlier, and I am sorry things got thus far. Both Jose and I were working on feature updates. 

While ideally we should be able to attend to all issues in a timely manner, we had to prioritize on issues directly related to PWA. Only if we had more time in our days, right? 

Regarding the question, I guess at this point you had deactivated / deleted SuperPWA? Note that the service worker is installed on the browser and that has to be removed manually. 

- You can do this by going to the `Application` tab of Chrome dev tools 
- Go to `Service Workers` and clicking `Unregister`. 
- Close the tab and re-open it. 

I see that you have a conversation going with Jose via email. Please feel free to send us things from your experience and we will look into it. 

Thanks again.

**Comment by coolrecep** [comment]
Thank you and sorry for my behaviour. It turned out to be a database problem. But the XenForo conflict still goes on and I need you to take a look at it. 

Thank you.

**Comment by arunbasillal** [comment]
Aw, thank you! Glad you could figure it out. 

Its a bit too late in my day, I have added your case to my todo for tomorrow, so I will definitely look into it. 

Thanks again.
