### ISSUE TITLE
CTA banner display option "Show on Scroll" not working properly.

### ISSUE THREAD

**Issue by sajandara** [SuperPWA/Super-Progressive-Web-Apps#350]
The CTA banner display option "Show on Scroll" not working properly as it should show the banner after the visitor scroll down on the page but it is getting invisible as the visitor scrolls down on the page.

Ref ticket: https://magazine3.in/conversation/66978?folder_id=27

Ref video: https://monosnap.com/direct/CwmCyg1sdDj3XA3v8nBoCg1s8Pt812

**Comment by akshaywali** [comment]
Code updated at https://github.com/SuperPWA/super-progressive-web-apps-pro/commit/469fe2c16a41db81017ba95e0ed90fb6295e3f72

**Comment by akshaywali** [comment]
pushed in  PRO 1.23 update
