### ISSUE TITLE
User are unable to go to the previous page after visiting the Image.

### ISSUE THREAD

**Issue by sajandara** [SuperPWA/Super-Progressive-Web-Apps#355]
Users are unable to go to the previous page after visiting the image embedded in the WordPress block "button"

Ref video: https://monosnap.com/direct/XlDncG1BIm5oewa5NofDeUVKbCrpm2

Ref ticket: https://magazine3.in/conversation/70180?folder_id=27

**Comment by akshaywali** [comment]
There is limited support for PWA on iOS. 
iOS does not open link in WebView  instead it open it in PWA app with no navigation option if media file is in same domain. On Android it is working fine. This is known issue which as of now has no solutions  except waiting for iOS to support the feature.

**Comment by akshaywali** [comment]
Closing issue as of now .

**Comment by sajandara** [comment]
Another user is facing the same issue
https://magazine3.in/conversation/123719?folder_id=27
