### ISSUE TITLE
CTA button in menu is appearing in PWA even if user has downloaded the PWA.

### ISSUE THREAD

**Issue by sajandara** [SuperPWA/Super-Progressive-Web-Apps#356]
The CTA button in the menu is appearing in PWA even if the visitor has downloaded the PWA already.

Ref video: https://monosnap.com/file/90KRyHFbWzR4rXG6ZC2DQhkycSpNgZ

Ref ticket: https://magazine3.in/conversation/66978?folder_id=27

**Comment by akshaywali** [comment]
pushed in  PRO 1.23 update

**Comment by sajandara** [comment]
The issue is reoccurring
Ref ticket: https://magazine3.in/conversation/104824?folder_id=27
Ref screenshot: https://monosnap.com/direct/n42aftXNUUO7vhSEKA8oiuhnGAyCIr

**Comment by akshaywali** [comment]
Issue will be fixed in this ticket https://github.com/SuperPWA/Super-Progressive-Web-Apps/issues/381
