### ISSUE TITLE
CTA shortcode feature not working in android

### ISSUE THREAD

**Issue by MohammedAkramU7** [SuperPWA/Super-Progressive-Web-Apps#357]
Ref URLs:-
https://magazine3.in/conversation/58108?folder_id=21
https://magazine3.in/conversation/67738?folder_id=21

Issue screenshot:-
https://prnt.sc/cevMqXSR8-QY

**Comment by akshaywali** [comment]
Since issue can't be recreated so waiting for user login

**Comment by akshaywali** [comment]
Issue is user specific , and user is not replying . So closing this issue for now
