### ISSUE TITLE
An error with SuperPWA is displayed while testing in the Page speed dev tool. 

### ISSUE THREAD

**Issue by Sdaud1950** [SuperPWA/Super-Progressive-Web-Apps#362]
An error appears under "Best Practices" for mobile devices when performing website testing at https://pagespeed.web.dev/.

Ref screenshot: https://prnt.sc/rx83_2ga2wC4

Ref ticket:  https://magazine3.in/conversation/75666?folder_id=29

**Comment by akshaywali** [comment]
pushed in 2.2.10 update
