### ISSUE TITLE
CTA menu button warning on IOS only appears in the English language.

### ISSUE THREAD

**Issue by sajandara** [SuperPWA/Super-Progressive-Web-Apps#363]
Bug Name: CTA menu button warning on IOS only appears in the English language.

Version Number: 2.2.9.1

Issue reported by: User

Reference ticket: https://magazine3.in/conversation/73465?folder_id=27

Description: The CTA menu button warning on IOS only appears in the English language even if the website's default language is Italian or some other language.

Reference screenshot: https://prnt.sc/xGxv_PWfvL3X

User's suggestion: The warning should appear in the default language of the website, or in the language that the visitor is reading.

**Comment by akshaywali** [comment]
Issue fixed https://github.com/SuperPWA/super-progressive-web-apps-pro/commit/5794c807a640c97641c6a75add68e2e89ebb55a8

**Comment by akshaywali** [comment]
pushed in  PRO 1.23 update
