### ISSUE TITLE
The color of the APP icon is changing on the IOS device when we install the SuperPwa app.

### ISSUE THREAD

**Issue by Sdaud1950** [SuperPWA/Super-Progressive-Web-Apps#364]
Bug Name: The APP icon color is changing on the iOS device when we install the SuperPwa app.

Plugin Version: 2.2.9.1

Reference ticket: https://magazine3.in/conversation/66399?folder_id=29

Description: When we set the app icon image from the backend, it shows the same on the Android device, but on the iOS device, the color of the icon changes.

Ref screenshot 1. The icon color we have set is https://prnt.sc/sBTw0-j208U4.

Ref screenshot 2. The icon color shows on Android fine. https://prnt.sc/Uq2pUQXghkrL

Screenshot 3: The Icon Color Changes on iOS https://prnt.sc/UkkO5wvqAGbz

**Comment by akshaywali** [comment]
Please do not use transparent background in icons . Since iPhone will show black color where it finds transparency however it will work fine on android.
