### ISSUE TITLE
When we click on the Cancel CTA button and visit another page of the website, the CTA remains visible.

### ISSUE THREAD

**Issue by Sdaud1950** [SuperPWA/Super-Progressive-Web-Apps#367]
When we click on the Cancel CTA button and visit another page of the website, Still the CTA button shows.

Ref Video : https://monosnap.com/direct/S9vQJsHvJQvskmUrpoLNozh5MMiBQ1

Ref Ticket : https://magazine3.in/conversation/13249?folder_id=29

**Comment by akshaywali** [comment]
Issue fixed on SuperPWA PRO 1.24 https://github.com/SuperPWA/super-progressive-web-apps-pro/commit/d5203684eee2cf9eaa37405fdc6195d2c7f1ffbf
