### ISSUE TITLE
Preloader not working proper after recent update

### ISSUE THREAD

**Issue by 77naveenop** [SuperPWA/Super-Progressive-Web-Apps#368]
When clicking on an external link or trying to visit the page and going back to the preloader, it stays on the screen forever.

Reference ticket -: https://magazine3.in/conversation/81379?folder_id=23

**Comment by akshaywali** [comment]
Issue fixed on SuperPWA Pro https://github.com/SuperPWA/super-progressive-web-apps-pro/commit/03c1a26e08525fb139d85d299ea75b7fe311f91e
