### ISSUE TITLE
An empty space appears at the bottom of the page while scrolling through the content.

### ISSUE THREAD

**Issue by sajandara** [SuperPWA/Super-Progressive-Web-Apps#369]
Bug Name: An empty space appears at the bottom of the page while scrolling through the content.
Area Path: PWA
Version Number: 2.2.10
Reason: Bug
Issue reported by: User
Reference ticket: https://magazine3.in/conversation/83152?folder_id=27
Description: If the user has selected the option "Full Screen" under "Display", then an empty space appears at the bottom of the page while scrolling through the content.

Ref video: https://drive.google.com/file/d/1u6zyzVhOeJ4hkxHeKnqvHvrytP4Z-SJb/view

Steps to reproduce.

Activate the plugin and go to the settings
In the settings, you will find an option "Display", select "Full Screen" in that as shown in the screenshot https://prnt.sc/yXF7yWrxWSzG

**Comment by akshaywali** [comment]
The area is being added by the Android OS for softkeys although the softkeys are  hidden(since display mode is fullscreen).This Issue exists on android version <=10 and on specific models . 
**So this bug is related to Android OS and not our plugin.**
