### ISSUE TITLE
Preloader not working properly.

### ISSUE THREAD

**Issue by MohammedAkramU7** [SuperPWA/Super-Progressive-Web-Apps#375]
Ref ticket:- https://magazine3.in/conversation/88779?folder_id=21

Description:-
Preloader appears on the desktop when we enable the "Show in PWA" option.

Issue screenshot:-
https://monosnap.com/direct/8MhdK6jcZwxqBdkwFkRNveHOGcC4Hp

**Comment by akshaywali** [comment]
Issue fixed by  @77naveenop  https://github.com/SuperPWA/super-progressive-web-apps-pro/commit/58141571dd7603a99049a9892a7a97ab3694f6a9

**Comment by akshaywali** [comment]
Update pushed in SuperPWA PRO 1.26
