### ISSUE TITLE
The app icon is not showing the same as what we set in the backend.

### ISSUE THREAD

**Issue by Sdaud1950** [SuperPWA/Super-Progressive-Web-Apps#376]
When we set the application icon and click "Add to home screens," the application icon is not showing the state that we have set in the backend.

Ref video: https://monosnap.com/direct/DrhBt642RDPatrIBQlrlHiIxWdZxbs 

Ref Ticket: https://magazine3.in/conversation/90679?folder_id=29

**Comment by ScreenTag-Team** [comment]
This may be an issue with the emulator you are using. Have you tried to replicate it on a real device?

**Comment by akshaywali** [comment]
Issue was user specific , it is fixed on user site.
