### ISSUE TITLE
URL shown inside the APK

### ISSUE THREAD

**Issue by MohammedAkramU7** [SuperPWA/Super-Progressive-Web-Apps#377]
Ref ticket:- https://magazine3.in/conversation/88779?folder_id=21

Description:-
User generate android APK but URL shown inside the APK and standalone/fullscreen not working.

Issue screenshot:-
https://prnt.sc/zK52FT0PXBBg

**Comment by sajandara** [comment]
A user is facing the same issue.
https://magazine3.in/conversation/47782?folder_id=27

**Comment by akshaywali** [comment]
https://magazine3.in/conversation/47782?folder_id=27

User is  using PWA at root (https://example.com)and at sub directory (https://example.com/website).
There is a known issue that PWA at root overrides PWA at subdirectory so there was issue of  URL showing inside the app.
**Fix for this is to use combined assetlinks.json (root PWA + subdirectory PWA) at subdirectory folder**

**Comment by akshaywali** [comment]
https://magazine3.in/conversation/88779?folder_id=21

there was assetlinks.json regarding issue , it is now fixed in user side.
