### ISSUE TITLE
Drawing issue on Android

### ISSUE THREAD

**Issue by ScreenTag-Team** [SuperPWA/Super-Progressive-Web-Apps#378]
When a page is first loaded, drawing on the screen is done as if display mode was set to 'browser', without full browser UI shown (e.g. all elements on the page are pushed lower on the screen by some 30px, and an element positioned at top 0px is shown at some top 30px). If the user goes to refresh the page, elements are then correctly positioned - and continue to be correctly positioned, no matter how many times the page is refreshed; the issue is only present the first time a page is loaded.

Testing with a full-screen browser presented the page as intended, with no issues - so, this is not a styling issue due to CSS or HTML.

**Comment by akshaywali** [comment]
@ScreenTag-Team 
Can you specify which android version you are using and what is display mode  for PWA ?
It would be better if you can share some screenshot/video of the issue .

**Comment by akshaywali** [comment]
@ScreenTag-Team 
Still waiting for reply. If no reply is received by the end of week , this ticket would be marked as closed.

**Comment by akshaywali** [comment]
Closing this ticket since there is no response from the user
