### ISSUE TITLE
Generated APK is not getting downloaded

### ISSUE THREAD

**Issue by sajandara** [SuperPWA/Super-Progressive-Web-Apps#380]
Generated APK is not getting downloaded.

Ref video: https://monosnap.com/direct/yo3myXnZXRFUsT30kzruYFrHufzNTT

**Comment by akshaywali** [comment]
User **site_url** and **home_url**  in **settings page** were **http** but site was working on **https**.
When **site_url** and **home_url** were update to **https** issue got fixed .
