### ISSUE TITLE
CTA install banner is appearing even after installing the PWA

### ISSUE THREAD

**Issue by sajandara** [SuperPWA/Super-Progressive-Web-Apps#381]
CTA install banner is appearing even after installing the PWA

Ref ticket: https://magazine3.in/conversation/100918?folder_id=27

**Comment by akshaywali** [comment]
Fixed at SuperPWA Pro 1.27 https://github.com/SuperPWA/super-progressive-web-apps-pro/commit/7bed76aea9ceed8a3880c9c6688f686e881c7206

**Comment by akshaywali** [comment]
pushed in update SuperPWA Pro 1.27
