### ISSUE TITLE
   Changes are not automatically reflected when you make changes and update the service worker version. 

### ISSUE THREAD

**Issue by Sdaud1950** [SuperPWA/Super-Progressive-Web-Apps#384]
When we change the IOS splash screen icon and update the service worker version, the new IOS splash screen icon does not appear. It's showing the old icon.

Ref ticket: https://magazine3.in/conversation/104955?folder_id=29

**Comment by akshaywali** [comment]
Changes to name, short_name and icons are not currently supported on Android Chrome/ IOS Safari , 
Only change in background_color, display, orientation, scope, shortcuts, start_url, theme_color trigger change

In Android PWA will be updated  within 24 hrs change in manifest is detected.
After all windows of the PWA have been closed, the device is plugged in, and connected to WiFi, Chrome requests an updated WebAPK from the server. If Chrome is unable to get an updated manifest from the server, it may increase the time between checks to 30 days.

Source : https://web.dev/manifest-updates/
