### ISSUE TITLE
<a class="superpwa_add_home_close"> effect on SEO

### ISSUE THREAD

**Issue by MohammedAkramU7** [SuperPWA/Super-Progressive-Web-Apps#385]
Ref ticket:- https://magazine3.in/conversation/106262?folder_id=21

Description:
superpwa_add_home_close class effect on SEO as per Google and warring appear "Links are not crawlable" Search engines may use `href` attributes on links to crawl websites. Ensure that the `href` attribute of anchor elements links to an appropriate destination.

Issue screenshot:-
https://prnt.sc/hZanGVVluNB3

**Comment by akshaywali** [comment]
Code update in SuperPWA PRO 1.29 https://github.com/SuperPWA/super-progressive-web-apps-pro/commit/7e8cc8cb4be112759e4e4f66227954ed02145b22

**Comment by akshaywali** [comment]
Update pushed at SuperPWA Pro 1.29
