### ISSUE TITLE
Add related_applications to manifest

### ISSUE THREAD

**Issue by tagmood** [SuperPWA/Super-Progressive-Web-Apps#387]
please, add related_applications to get instruction to browser to install the native app

```
  "related_applications": [
    {
      "id":"com.package.id",
      "platform":"play",
      "url":"https://play.google.com/store/apps/details?id=com.package.id"
    }
  ],
  "prefer_related_applications": true,
```

**Comment by Sdaud1950** [comment]
the same feature this user requested: https://magazine3.in/conversation/125160?folder_id=29

**Comment by akshaywali** [comment]
pushed in SuperPWA 2.2.16

**Comment by tagmood** [comment]
it does not work

after filling the "PlayStore App ID" field, no related_application json appears on superpwa-manifest.json

could you double check it?
