### ISSUE TITLE
CTA banner's Install button is not working properly

### ISSUE THREAD

**Issue by sajandara** [SuperPWA/Super-Progressive-Web-Apps#389]
The CTA banner's Install button is not working properly, it works sometimes and sometimes it doesn't.

Ref tickets:
https://magazine3.in/conversation/108093?folder_id=27
https://magazine3.in/conversation/108491?folder_id=27

**Comment by akshaywali** [comment]
https://magazine3.in/conversation/108491?folder_id=27

Issue fixed by updating service worker version , issue was due to cache

**Comment by akshaywali** [comment]
fixed at user side
