### ISSUE TITLE
Conflict issue with Wolmart theme

### ISSUE THREAD

**Issue by MohammedAkramU7** [SuperPWA/Super-Progressive-Web-Apps#390]
Ref ticket:- https://magazine3.in/conversation/95614?folder_id=21

Description:-
When we activate the Call to Action addon, some of the WordPress theme functionality is not working.

Issue video:-
https://monosnap.com/file/Js2WyHcA9LNn9xQDPvJyqdxMh60AqW

**Comment by akshaywali** [comment]
Conflict fixed at SuperPWA PRO https://github.com/SuperPWA/super-progressive-web-apps-pro/commit/8b1700fe9cfac681b27ef0fb096794e7e6157981

**Comment by akshaywali** [comment]
Update pushed at SuperPWA Pro 1.29
