### ISSUE TITLE
Super PWA conflicts with the Real Media Library plugin.

### ISSUE THREAD

**Issue by Sdaud1950** [SuperPWA/Super-Progressive-Web-Apps#391]
When we activate the Real Media Library plugin, the Service Worker is not getting generated of SuperPWA, and the Add Home Screen is not showing.

Ref screenshot.https://prnt.sc/dtn2XhVCAuP3

Ref ticket:https://magazine3.in/conversation/108080?folder_id=29

**Comment by akshaywali** [comment]
Update pushed at SuperPWA 2.2.14
