### ISSUE TITLE
Call To Action banner should not be shown on inner page

### ISSUE THREAD

**Issue by 77naveenop** [SuperPWA/Super-Progressive-Web-Apps#392]
when user browse to an inner page the call to action DOES show up, it should not show up on an inner page because if the user installs from there he’ll always be taken to the inner page when opening the app.

Reference ticket - https://magazine3.in/conversation/81379?folder_id=23

**Comment by akshaywali** [comment]
![image](https://user-images.githubusercontent.com/36995680/228844080-8a74fe42-50bc-4332-8482-031ad8bd64fb.png)

Added option to show CTA on all pages OR  specific pages

**Comment by akshaywali** [comment]
Feature added at SUPERPWA PRO 1.29 https://github.com/SuperPWA/super-progressive-web-apps-pro/commit/5639018c095ea95ea451a8201c52148602aac8f7

**Comment by akshaywali** [comment]
Update pushed at SuperPWA Pro 1.29
