### ISSUE TITLE
User website video is not working while using the superPWA offline

### ISSUE THREAD

**Issue by Sdaud1950** [SuperPWA/Super-Progressive-Web-Apps#393]
User website video is not working while using the superPWA offline

Ref ticket : https://magazine3.in/conversation/108080?folder_id=29

**Comment by akshaywali** [comment]
User was using big video file which was taking time to get cached (it was loading as partial content ) , while video was being cached if  we go offline video was not available to play .
 User has acknowledged this and said video is working after waiting for sometime.

**Comment by akshaywali** [comment]
Solved at user side
