### ISSUE TITLE
Conflict with CHP ads block detector

### ISSUE THREAD

**Issue by Sasirekhamarella** [SuperPWA/Super-Progressive-Web-Apps#399]
Scenario: Getting fatal error due to conflict with CHP ads block detector

`Fatal error: Uncaught Error: Call to a member function get() on array in /home/customer/www/garage1.magazine3.com/public_html/wp-content/plugins/chp-ads-block-detector/includes/scripts.php:78 Stack trace: #0 /home/customer/www/garage1.magazine3.com/public_html/wp-includes/class-wp-hook.php(308): CHPADB\Includes\scripts->css('') #1 /home/customer/www/garage1.magazine3.com/public_html/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters(NULL, Array) #2 /home/customer/www/garage1.magazine3.com/public_html/wp-includes/plugin.php(517): WP_Hook->do_action(Array) #3 /home/customer/www/garage1.magazine3.com/public_html/wp-includes/general-template.php(3043): do_action('wp_head') #4 /home/customer/www/garage1.magazine3.com/public_html/wp-content/themes/twentytwentyone/header.php(20): wp_head() #5 /home/customer/www/garage1.magazine3.com/public_html/wp-includes/template.php(783): require_once('/home/customer/...') #6 /home/customer/www/garage1.magazine3.com/public_html/wp-includes/template.php(718): load_template('/home/customer/...', true, Array) #7 /home/customer/www/garage1.magazine3.com/public_html/wp-includes/general-template.php(48): locate_template(Array, true, true, Array) #8 /home/customer/www/garage1.magazine3.com/public_html/wp-content/themes/twentytwentyone/page.php(12): get_header() #9 /home/customer/www/garage1.magazine3.com/public_html/wp-includes/template-loader.php(106): include('/home/customer/...') #10 /home/customer/www/garage1.magazine3.com/public_html/wp-blog-header.php(19): require_once('/home/customer/...') #11 /home/customer/www/garage1.magazine3.com/public_html/index.php(17): require('/home/customer/...') #12 {main} thrown in /home/customer/www/garage1.magazine3.com/public_html/wp-content/plugins/chp-ads-block-detector/includes/scripts.php on line 78`

Reference ticket: https://wordpress.org/support/topic/problem-with-chp-ads-block-detector-plugin/

**Comment by akshaywali** [comment]
Update pushed at SuperPWA 2.2.14
