### ISSUE TITLE
QR code is not working

### ISSUE THREAD

**Issue by Sdaud1950** [SuperPWA/Super-Progressive-Web-Apps#400]
When we scan the QR code, it redirects to the URL, but when we click on the Install button, nothing happens.

Ref Video: https://monosnap.com/direct/MQ7wQgOBsz8BodY7Ed8iG94Uat8Q53 

Ref Ticket: https://magazine3.in/conversation/114347?folder_id=29

**Comment by akshaywali** [comment]
Update pushed at SuperPWA PRO 1.29 https://github.com/SuperPWA/super-progressive-web-apps-pro/commit/aeac1f3008fee545650d8d7e08928a52691b6f44

**Comment by akshaywali** [comment]
Update pushed at SuperPWA Pro 1.29
