### ISSUE TITLE
 Need to create an option where the user can show the add-to-screen banner for particular pages.

### ISSUE THREAD

**Issue by Sdaud1950** [SuperPWA/Super-Progressive-Web-Apps#402]
There is a need to create an option where users can set add to home-screen banners for specific pages. When a user sets a banner for a specific page, it should not appear on other pages or posts.

https://magazine3.in/conversation/122760?folder_id=29

**Comment by akshaywali** [comment]
Feature added inSUPERPWA PRO 1.29 https://github.com/SuperPWA/super-progressive-web-apps-pro/commit/5639018c095ea95ea451a8201c52148602aac8f7

**Comment by akshaywali** [comment]
![image](https://user-images.githubusercontent.com/36995680/229267605-0b377511-5251-47c2-a0f2-f4591c5f91d0.png)

**Comment by akshaywali** [comment]
Update pushed at SuperPWA Pro 1.29
