### ISSUE TITLE
Need to add push notification feature in IOS

### ISSUE THREAD

**Issue by ankit644** [SuperPWA/Super-Progressive-Web-Apps#403]
Ref:- https://magazine3.in/conversation/52388?folder_id=11

**Comment by Sasirekhamarella** [comment]
Another req: https://wordpress.org/support/topic/push-notification-for-ios-apps/

**Comment by Sanjeevsetu** [comment]
Hi @ilpincio85 

We have just added support for push notification in last update. Try new version and go to add-on section.
