### ISSUE TITLE
CSS of the website is not getting loaded if the option caching first then network is selected

### ISSUE THREAD

**Issue by sajandara** [SuperPWA/Super-Progressive-Web-Apps#408]
CSS of the website is not getting loaded if the option caching first then network is selected.

Ref screenshot:  https://prnt.sc/6U26C9lGAE14

Ref ticket: https://magazine3.in/conversation/119716?folder_id=27

**Comment by akshaywali** [comment]
pushed in SuperPWA 2.2.15
