### ISSUE TITLE
Need to create an option where users can exclude a particular page from the PWA.

### ISSUE THREAD

**Issue by Sdaud1950** [SuperPWA/Super-Progressive-Web-Apps#429]
Need to create an option where users can exclude a particular page from the PWA.

Ref Ticket: https://magazine3.in/conversation/143490?folder_id=29

**Comment by Sdaud1950** [comment]
same requirement .
https://magazine3.in/conversation/202948?folder_id=29

**Comment by kumawatvikas** [comment]
Ref : https://github.com/SuperPWA/super-progressive-web-apps-pro/commit/6a8c1fe79565ef92a1f6e209da0850c2abed6b41
