### ISSUE TITLE
 Need to  show push notification" in the PWA APK.

### ISSUE THREAD

**Issue by Sdaud1950** [SuperPWA/super-progressive-web-apps#431]
Need to show push notification" in the PWA APK.

Ref ticket: https://magazine3.in/conversation/145485?folder_id=29

**Comment by akshaywali** [comment]
This feature depends on Push notification for WP plugin , so it will be available as update for  [Push Notifications for WP](https://wordpress.org/plugins/push-notification/)  1.40  is released. Will be closing this ticket  for now
