### ISSUE TITLE
Conflict issue with OceanWP Child Theme

### ISSUE THREAD

**Issue by MohammedAkramU7** [SuperPWA/Super-Progressive-Web-Apps#433]
Ref ticket: https://magazine3.in/conversation/148326?folder_id=21

Description:-
CTA not working properly with ocean wp child theme install button is not clickable and CTA not visible after install.

Issue screenshot
https://prnt.sc/dSamzUhlaE1N

**Comment by Sanjeevsetu** [comment]
Issue is not being created at our end and user has not cooperated us. I am closing it, If issue still there and need help create new ticket
