### ISSUE TITLE
Showing Splashscreen ICON instead of Application ICON

### ISSUE THREAD

**Issue by Sasirekhamarella** [SuperPWA/Super-Progressive-Web-Apps#434]
When we installed the APP, It should show Application Icon but it is showing Splashscreen Icon when we added the app to the home screen. Not working properly.

Here is the reference ticket: https://wordpress.org/support/topic/aplication-icon-vs-splas-screen/

**Comment by Sasirekhamarella** [comment]
https://wordpress.org/support/topic/app-icon-and-splash-not-working/

**Comment by jasonb4u** [comment]
Also it doesn't offer to download App on Apple devices

**Comment by GitStudying** [comment]
As many others I have the same problem. In commit f0f905d it seems to have removed the maskable part of the splash icon, which I am not sure but had a suspicion causes this issue.
In some posts superPWA says this is not limited to them but as a result of Google change to interpration of icons. 
I am not sure what it is, either way it would already be better if the information would be more clear. If it isn't a bug on SuperPWA side, then update the details surrounding the icons inside of the interface. For example say the splash screen is currently used both for splash and application icons on the home screen of at least Android devices.
Users expect the application icon to be proper icon but the splash icon is used instead causing usage issues.

**Comment by Sanjeevsetu** [comment]
Related https://github.com/SuperPWA/Super-Progressive-Web-Apps/issues/540
