### ISSUE TITLE
Preloader is not working on IOS devices

### ISSUE THREAD

**Issue by sajandara** [SuperPWA/Super-Progressive-Web-Apps#435]
Bug: Preloader not working on IOS device(PWA/Website)
Plugin version: 2.2.17 | PRO: 1.32 
Reference ticket: https://magazine3.in/conversation/149593?folder_id=27

**Comment by RaversUnited** [comment]
Any idea to fix the issue ?

**Comment by Sdaud1950** [comment]
Same issue : https://magazine3.in/conversation/163141?folder_id=29

**Comment by akshaywali** [comment]
Fix Pushed in SuperPWA PRO 1.34
