### ISSUE TITLE
PWA Display mode is not respected with SuperPWA Pro Android APK app

### ISSUE THREAD

**Issue by dwise85** [SuperPWA/Super-Progressive-Web-Apps#436]
I set my app's display mode to "Standalone" for minimal UI when the end user installs the PWA. However, after trying to utilize the PWA Pro feature, I observed the generated APK is running in "Minimal" display mode, which is much worse as it takes up a lot of screen real estate.

![image](https://github.com/SuperPWA/Super-Progressive-Web-Apps/assets/2475800/76e316a6-29f7-4854-aeaf-a3405fb83a06)

When installed as an APK on my Android phone for testing it appears exactly as described as "Minimal" display mode as described here:
https://superpwa.com/doc/web-app-manifest-display-modes/?utm_source=superpwa-plugin&utm_medium=settings-display

This tells me my setting isn't respected. When I install the PWA through Chrome, it does appear as "Standalone" as I'd expect.

**Comment by akshaywali** [comment]
@dwise85  It seems that you are talking about top bar displaying in the APK . 
https://superpwa.com/docs/article/my-apk-is-showing-top-bar-address-url-bar/
Complete these step otherwise top bar will always be displayed.
Please do update if the issue is fixed.

**Comment by Sanjeevsetu** [comment]
Closing the ticket due to inactivity. Still have an issue, Please create a new ticket or contact us.
