### ISSUE TITLE
Installation Failed

### ISSUE THREAD

**Issue by karasnj** [SuperPWA/Super-Progressive-Web-Apps#44]
I received the following upon attempting to install the wordpress plugin.  I do not know if it is somehow related to the issue, but I have a plugin installed which is a web app called "Active Demand" that most of the pages are truly running on through its landing page creator.  There are also many autoplay videos embedded into those landing pages.  Other than that I am not aware of any other potential conflicts.  Please advise. Thanks

Installation failed: body {font-family: 'Helvetica', Sans-Serif;text-align: center;background-color: #77c043;color: #fff;}.container {position: relative;top: 50%;transform: translateY(-50%);}.subheader {font-size: 16px;line-height: 22px;font-weight: normal;margin: 20px auto;text-align: left;width: 500px;font-weight: 200;}502 (Bad Gateway) ErrorSomething&#39;s gone wrong, but it&#39;s likely temporary. Try refreshing the page, but it&#39;d be best to try back later.This page error has the following parameters:clientIP - ::ffff:173.72.44.155gatewayHostname - starkgate-p11.cloud.phx3.gdgoriginDomain - butlerdelivers.comresolvedOriginDomain - butlerdelivers.com

**Comment by arunbasillal** [comment]
Hello @karasnj 

It's a 502 bad gateway error. It's not related to WordPress or SuperPWA. Can you try again a bit later or in a different browser?

**Comment by karasnj** [comment]
I did so and it did install.  Thanks!
