### ISSUE TITLE
Conflcit with the bunny.net plugin

### ISSUE THREAD

**Issue by Sdaud1950** [SuperPWA/Super-Progressive-Web-Apps#441]
While using the bunny.net plugin, the Add to Home Screen banner is not showing, and it shows the error and a warning in the manifest.

Ref screenshoot: https://prnt.sc/0a9pXCnQjmE3

Ref Ticket: https://magazine3.in/conversation/154649?folder_id=29

**Comment by Sanjeevsetu** [comment]
Issue does not seem to valid. There was settings issue at user end.
