### ISSUE TITLE
CTA is not working in opera browser

### ISSUE THREAD

**Issue by MohammedAkramU7** [SuperPWA/Super-Progressive-Web-Apps#444]
Ref ticket:-https://magazine3.in/conversation/161645?folder_id=21

Description:-
When we enable the iOS and desktop options, then only CTA works. When we uncheck the desktop option, the CTA is not visible in the Opera browser.

Setting screenshot
https://prnt.sc/GM9sLf0z5wFp.

**Comment by akshaywali** [comment]
PWA installation is only available if the user browses your website from Safari.
 
https://web.dev/learn/pwa/installation#:~:text=It's%20important%20to%20understand%20that,PWA%20on%20the%20home%20screen.
