### ISSUE TITLE
Need to add support to display badge on mobile PWA icon

### ISSUE THREAD

**Issue by 77naveenop** [SuperPWA/Super-Progressive-Web-Apps#447]
When there is any notification, PWA need to show badge on Icon of PWA.

Reference ticket -:  https://magazine3.in/conversation/162721?folder_id=23

reference link -: https://developer.mozilla.org/en-US/docs/Web/Progressive_web_apps/How_to/Display_badge_on_app_icon

**Comment by Sanjeevsetu** [comment]
This is same as https://github.com/SuperPWA/Super-Progressive-Web-Apps/issues/212 so I am closing it
