### ISSUE TITLE
Need to add an option to set start_url dynamically.

### ISSUE THREAD

**Issue by 77naveenop** [SuperPWA/Super-Progressive-Web-Apps#449]
If add "add_to_home" button to a certain page, it will set the specific page as the start_url.

**Comment by akshaywali** [comment]
Add to home behaves differently in IOS and Android. In iOS the page on which add to home is performed becomes start URL but in Android start URL is taken from manifest.

According to the request we can make current URL as start URL. In that case after the user has added the app, start URL will constantly change and app opens with a new start URL (usually app gets updated within 48hrs after the manifest has changed).
So this is not a ideal feature for production app. so closing this ticket .
