### ISSUE TITLE
Error mixed http vs Https

### ISSUE THREAD

**Issue by Iraecio** [SuperPWA/Super-Progressive-Web-Apps#46]
ServiceWork function over https 

And spwa generate register-sw.js over http.

function superpwa_register_sw()
{
    //need change here
    wp_enqueue_script('superpwa-register-sw', SUPERPWA_PATH_SRC . 'public/js/register-sw.js', array(), null, true);
    wp_localize_script('superpwa-register-sw', 'superpwa_sw', array(
            'url' => superpwa_sw('src'),
        )
    );
}

Work for me this

function superpwa_register_sw()
{
    //replace http by https
    $url = preg_replace("/^http:/i", "https:", SUPERPWA_PATH_SRC . 'public/js/register-sw.js');

    wp_enqueue_script('superpwa-register-sw', $url, array(), null, true);
    wp_localize_script('superpwa-register-sw', 'superpwa_sw', array(
            'url' => superpwa_sw('src'),
        )
    );
}

**Comment by arunbasillal** [comment]
Hello @Iraecio, thanks for your feedback. 

Are you using a SSL redirection plugin like really simple SSL?

The URL to the register-sw.js appears on the front end and should be https. Can you point me to the website where you are seeing this?

**Comment by Iraecio** [comment]
https://guianortao.com.br

**Comment by Iraecio** [comment]
Yes, I'm using my own code. changing http by https

I downloaded the repository and extract it into the plugins folder.

I tested the installation by wordpress today. It worked correctly by leaving https as default.

I do not know why it did not work manually.

**Comment by arunbasillal** [comment]
Very strange indeed. 

You can check it by checking the value of `SUPERPWA_PATH_SRC` in `superpwa.php` in the old setup. 

Glad to hear its working correctly now! :+1:
