### ISSUE TITLE
Need to target Android 13 (API level 33) or higher

### ISSUE THREAD

**Issue by 77naveenop** [SuperPWA/Super-Progressive-Web-Apps#464]
Google Play Console telling that the Google Play Target API Level requirements affect my apps. Need to fix apps because they need to target Android 13 (API level 33) or higher.

Reference user -: https://magazine3.in/conversation/175478?folder_id=23

**Comment by sajandara** [comment]
A user is facing the same issue: 
https://magazine3.in/conversation/175220?folder_id=27

**Comment by MohammedAkramU7** [comment]
Another user facing same issue:
https://magazine3.in/conversation/175515?folder_id=21

**Comment by MohammedAkramU7** [comment]
Another user facing issue
https://magazine3.in/conversation/175442?folder_id=21

**Comment by MohammedAkramU7** [comment]
Another user:- 
https://magazine3.in/conversation/177468?folder_id=21

**Comment by Sdaud1950** [comment]
Another user:
https://magazine3.in/conversation/113543?folder_id=29

**Comment by akshaywali** [comment]
API level updated to 33 on server
