### ISSUE TITLE
The push notification add-on keeps on installing.

### ISSUE THREAD

**Issue by Sdaud1950** [SuperPWA/Super-Progressive-Web-Apps#465]
When push notification plugin is not installed and we click on push notification add-on, it keeps installing...

Ref screenshoot: https://prnt.sc/vCV_PLaoU_YN

**Comment by jeriss-cloud-center** [comment]
Same for me here

**Comment by MohammedAkramU7** [comment]
Another user :- https://magazine3.in/conversation/189187?folder_id=21

**Comment by jeriss-cloud-center** [comment]
Any idea when this would be fixed? It's critical please
