### ISSUE TITLE
Add a new feature "CTA appearance should be able to be configured as Role Based"

### ISSUE THREAD

**Issue by sajandara** [SuperPWA/Super-Progressive-Web-Apps#467]
Add a new feature "CTA appearance should be able to be configured as Role Based"

Ref ticket: https://magazine3.in/conversation/189817?folder_id=27

**Comment by kumawatvikas** [comment]
https://github.com/SuperPWA/super-progressive-web-apps-pro/commit/1e4d31bdcf297f0534e4bd853273346b5cc1530b

**Comment by Sanjeevsetu** [comment]
What user exactly wanting is not clear and user is not replying so I am closing it.
