### ISSUE TITLE
Push notification issue with iOS and Dekstop

### ISSUE THREAD

**Issue by Sdaud1950** [SuperPWA/Super-Progressive-Web-Apps#474]
1. When PWA shows the notification, but after clicking the notification, it still shows on the PWA aap.

2. When we create a new post, the notification shows the first html line of the post. 

Ref ticket: https://magazine3.in/conversation/187110?folder_id=29

**Comment by Sanjeevsetu** [comment]
This has been solved and fixed in v. 2.2.21
