### ISSUE TITLE
Accessibility Warning: Snackbar Aria Label Issue in Lighthouse

### ISSUE THREAD

**Issue by askcode21** [SuperPWA/Super-Progressive-Web-Apps#477]
User reported that lines of code added by the plugin are causing an accessibility warning in Google Lighthouse.

Reference ticket: https://wordpress.org/support/topic/aria-label-for-snackbar-causing-accessibility-warning-in-lighthouse/

**Comment by akshaywali** [comment]
issue Fixed by commit https://github.com/SuperPWA/Super-Progressive-Web-Apps/commit/f51f0dd84f1f0b611ba4535626603d9429305f61

**Comment by akshaywali** [comment]
pushed in version 2.2.23
