### ISSUE TITLE
Styles for offline page

### ISSUE THREAD

**Issue by ecurtis** [SuperPWA/Super-Progressive-Web-Apps#48]
First of all thank you for this plugin - it is working quite well.

The only issue I currently have, and this may be on my end since we are using Timber and webpack inside the template, is that the page I selected for offline viewing displays without the CSS and JS (it was not visited prior)

Perhaps this is expected, and if/when the ability to cache pages the user has not gone to becomes part of the plugin we will be set.

I would love to know any thoughts on this. Currently the site is not public, I can share it in a few weeks if needed.

**Comment by ecurtis** [comment]
It makes perfect sense. Thank you for the response and for looking into it.

**Comment by arunbasillal** [comment]
Hello @ecurtis 

I have just released SuperPWA 1.9 and there is a filter `superpwa_sw_files_to_cache` to accommodate these things. 

Please see: https://github.com/SuperPWA/Super-Progressive-Web-Apps/blob/a06f52e1b0ddb74057ffb6d22545a9ae285ffe12/public/sw.php#L109

Hope that helps your cause.

**Comment by ecurtis** [comment]
Thank you!
