### ISSUE TITLE
An error is appearing in the lighthouse report

### ISSUE THREAD

**Issue by sajandara** [SuperPWA/Super-Progressive-Web-Apps#483]
An error is appearing in the lighthouse report

Ref ticket: https://magazine3.in/conversation/218609?folder_id=27

Ref screenshot: https://monosnap.com/direct/PuDseOzTH2A3Y1uQQlvnxlxpp41AQX

**Comment by Sanjeevsetu** [comment]
It has been fixed and pushed in v2.2.23
