### ISSUE TITLE
 Need to change the error message while creating an APK.

### ISSUE THREAD

**Issue by Sdaud1950** [SuperPWA/Super-Progressive-Web-Apps#494]
1. While creating an APK, there is an error message that is added below. We need to make a modification to that.
2 When we add the image icon in different languages, then there is an issue showing while generating the APK.

APK not created try later.
ErrorDetails: Error generating app package: Request path contains unescaped characters code: ERR_UNESCAPED_CHARACTERS stack: TypeError: Request path contains unescaped characters at new NodeError (node:internal/errors:393:5) at new ClientRequest (node:_http_client:182:13) at request (node:https:360:10) at /srv/updated-app-builder/node_modules/node-fetch/lib/index.js:1438:15 at new Promise () at Function.fetch [as default] (/srv/updated-app-builder/node_modules/node-fetch/lib/index.js:1407:9) at FetchUtils.fetch (/srv/updated-app-builder/node_modules/@bubblewrap/core/dist/lib/FetchUtils.js:35:46) at ImageHelper.fetchIcon (/srv/updated-app-builder/node_modules/@bubblewrap/core/dist/lib/ImageHelper.js:93:56) at TwaGenerator.generateIcons (/srv/updated-app-builder/node_modules/@bubblewrap/core/dist/lib/TwaGenerator.js:210:45) at TwaGenerator.createTwaProject (/srv/updated-app-builder/node_modules/@bubblewrap/core/dist/lib/TwaGenerator.js:331:24)

**Comment by akshaywali** [comment]
Pushed in SuperPWA Pro 1.38
