### ISSUE TITLE
Shortcode button is not a button til you touch it.

### ISSUE THREAD

**Issue by lhassell** [SuperPWA/Super-Progressive-Web-Apps#498]
We have our call to action install button in a sidebar. The concern is that until you touch the button, it is just black text on a white background.

Example:
![Screenshot_20240214-213246](https://github.com/SuperPWA/Super-Progressive-Web-Apps/assets/39358996/1f91b2cd-6cfa-45f7-8fc1-cb752298ac56)
 Is there a way to disable the mouseover so it always looks like this:
![Screenshot_20240214-213508](https://github.com/SuperPWA/Super-Progressive-Web-Apps/assets/39358996/add63fab-2ebc-4f67-af63-564bd2269d82)

**Comment by Sanjeevsetu** [comment]
Hi @lhassell 

Could you please share your website url so that we can check the issue?
