### ISSUE TITLE
CTA on the frontpage is not showing. 

### ISSUE THREAD

**Issue by Sdaud1950** [SuperPWA/Super-Progressive-Web-Apps#499]
When we enable the CTA on the homepage, then the CTA is not showing on the Homepage.

Ref ticket : https://magazine3.in/conversation/244668?folder_id=29

**Comment by Sanjeevsetu** [comment]
Ref https://github.com/SuperPWA/super-progressive-web-apps-pro/commit/2bb1470885942595f62b02e6e91c6b01e90399c1
