### ISSUE TITLE
The Superpwa service worker is overriding the push notification from the BracketSpace service worker.    

### ISSUE THREAD

**Issue by Sdaud1950** [SuperPWA/Super-Progressive-Web-Apps#504]
The Superpwa service worker is overriding the push notification from the BracketSpace service worker and user Use the extension push of the push notification.

Ref ticket : https://magazine3.in/conversation/252201?folder_id=29

**Comment by Sanjeevsetu** [comment]
We are unable to re create the issue and user has moved from it so closing it
