### ISSUE TITLE
The APK logo and the splash screen icon logo are not showing properly. 

### ISSUE THREAD

**Issue by Sdaud1950** [SuperPWA/Super-Progressive-Web-Apps#508]
The APK logo and the splash screen icon logo are not showing properly. 

Ref tciket : https://magazine3.in/conversation/236135?folder_id=29

Ref ticket:https://magazine3.in/conversation/256125?folder_id=29

**Comment by akshaywali** [comment]
pushed in SuperPWA  PRO 1.38
