### ISSUE TITLE
 Need to create a feature to add APKs to the iOS App Store.

### ISSUE THREAD

**Issue by Sdaud1950** [SuperPWA/super-progressive-web-apps#516]
Need to create a feature to add APKs to the iOS App Store.

Ref Ticket : https://magazine3.in/conversation/236135?folder_id=29

**Comment by MohammedAkramU7** [comment]
Another user: https://magazine3.in/conversation/274424?folder_id=21

**Comment by sajandara** [comment]
Another user with the feature request:
https://magazine3.in/conversation/309133?folder_id=27
