### ISSUE TITLE
Add all missing translation in SuperPwa pro extension

### ISSUE THREAD

**Issue by Sanjeevsetu** [SuperPWA/Super-Progressive-Web-Apps#518]

**Comment by Sanjeevsetu** [comment]
Ref user : https://magazine3.in/conversation/266046?folder_id=3

**Comment by kumawatvikas** [comment]
Ref  : https://github.com/SuperPWA/super-progressive-web-apps-pro/commit/37e012ef1a0bc234c31ecf3633680c730700d567
