### ISSUE TITLE
Getting console error and superPWA is not working

### ISSUE THREAD

**Issue by iamdharmesh** [SuperPWA/Super-Progressive-Web-Apps#52]
Hello There, 

First of all thanks for great plugin but its not working for me maybe some mistake, but I am not able to figure out whats going wrong.

Can you please take a look at error and my staging website https://v30.knawat.com/

`Service worker event waitUntil() was passed a promise that rejected with 'InvalidStateError: An attempt was made to use an object that is not, or is no longer, usable'.
superpwa-sw.js:18:1
TypeError: ServiceWorker script at https://v30.knawat.com/superpwa-sw.js for scope https://v30.knawat.com/ encountered an error during installation.`
 
screenshot.
![pwa_error](https://user-images.githubusercontent.com/10613171/42373402-696ab34e-8132-11e8-9d0f-facae7d1d349.png)

Thanks for your time. 

Best regards, 
Dharmesh Patel

**Comment by josevarghese** [comment]
Hi @iamdharmesh 

I checked your website and noticed that all the features of PWA are working perfectly. Have you tested the PWA on any mobile? 

Also upon Google Chrome console I cannot notice such an error which you mentioned, so can you please let me know at which page you noticed this error?

Looking forward.

**Comment by iamdharmesh** [comment]
Hello @josevarghese, 

Thanks a lot for quick response. Yes, you are right its working fine in chrome browser but getting an error in Firefox browser. can you please check in firefox browser. 

Also, we are moving our site to a bedrock structure. https://dev.knawat.io/ and getting same error there. So, is it because of that site URL contain '/wp/'?

Thanks for your help. let me know if you need any other information.

Best Regards, 
Dharmesh Patel

**Comment by josevarghese** [comment]
Thanks for letting know @iamdharmesh . This has been an issue for a few of our users, so we're looking into alternate ways. Nothing is available at this moment. I’ll update this thread when there is one and you can also see a solution provided by an user on our [WordPress directory.](https://wordpress.org/support/topic/chrome-works-fine-but-firefox-js-error/) We haven’t tested it, as we're currently working on our website and on support. We'll look over it on coming days and will release a fix for this on coming version.

Regarding the bedrock you're right, as the structure of Bedrock is comparatively different from WordPress, our plugin is not compatible with it till this time.  We're looking into by creating a dynamic file generation method. 

I'll keep you updated, once we made a fix for these issues.

**Comment by iamdharmesh** [comment]
Hello @josevarghese,

Thanks for your reply. 

I will check the support ticket link you have given and will try to fix the issue if any of that will work for me then I will update here.

Also, I will try to fix the issue regarding bedrock and if get any luck then surely update you here.

Thanks,
Dharmesh Patel

**Comment by iamdharmesh** [comment]
Hello @josevarghese,

Replacing `return cache.addAll(filesToCache);` with below code in superpwa-sw.js file worked for me.

```
filesToCache.map(function (url) {
    return cache.add(url).catch(function (reason) {
        return console.log(url + 'failed: ' + String(reason));
    });
}); 
```

Thanks,
Dharmesh Patel

**Comment by josevarghese** [comment]
@iamdharmesh Thanks for your reply and happy to hear the solution helped! We'll roll out the next release with a fix for this.

**Comment by arunbasillal** [comment]
Hey @iamdharmesh 

I was testing this out and it works perfectly. However, I noticed that your service worker still shows `return cache.addAll(filesToCache);`. 

Did you revert it back? Or maybe the service worker was overwritten? (SuperPWA regenerates the service worker when you change settings in the admin). 

I am getting ready to ship this in the next version. Just wondering if you reverted back because you noticed something else. Please let me know.

**Comment by arunbasillal** [comment]
I have added this to SuperPWA 1.9. It should be good now :)

**Comment by arunbasillal** [comment]
Thanks for your help @iamdharmesh :+1:
