### ISSUE TITLE
Fatal error while activating Superpwa Navigation Bar addon

### ISSUE THREAD

**Issue by 77naveenop** [SuperPWA/Super-Progressive-Web-Apps#525]
PHP Fatal error: Uncaught Error: Undefined constant "NBFS_PLUGIN_DIR" in /wp-content/plugins/super-progressive-web-apps-pro/addons/navigation_bar/include/library/font-svg.php:51

Reference user : https://magazine3.in/conversation/272821?folder_id=3

**Comment by Sanjeevsetu** [comment]
This issue has been fixed and pushed in SuperPwa pro v1.41.1
