### ISSUE TITLE
While clicking on the install button on CTA, the Google search appears for the word Install (Android only)

### ISSUE THREAD

**Issue by sajandara** [SuperPWA/Super-Progressive-Web-Apps#527]
While clicking on the install button on CTA, the Google search appears for the word Install (Android only)

Ref ticket: https://magazine3.in/conversation/267493?folder_id=27

**Comment by kumawatvikas** [comment]
Ref : https://github.com/SuperPWA/super-progressive-web-apps-pro/commit/7bbd2b1697e3567b74997957d9f397ad6fcf0b5e

**Comment by akshaywali** [comment]
pushed in SuperPWA PRO 1.43
