### ISSUE TITLE
Session got logout when user go out of PWA

### ISSUE THREAD

**Issue by 77naveenop** [SuperPWA/Super-Progressive-Web-Apps#528]
When we logged in PWA and then after going out from it and after clearing cache, when again go through PWA then it automatically got logout.

Reference user -:https://magazine3.in/conversation/274975?folder_id=23

**Comment by Sanjeevsetu** [comment]
This issue seems invalid. It works perfectly and user is using SuperPwa so I am closing it

**Comment by Sanjeevsetu** [comment]
The issue is not valid. There was some setup issue at user end and now it works fine.
