### ISSUE TITLE
Need to create an option to edit the text in the iOS QR code.

### ISSUE THREAD

**Issue by Sdaud1950** [SuperPWA/Super-Progressive-Web-Apps#529]
We need to create an option to edit the text in the iOS QR code.

Ref screenshoot: https://prnt.sc/cIfy7MwBFwDQ 

Ref ticket:https://magazine3.in/conversation/277234?folder_id=29

**Comment by kumawatvikas** [comment]
Ref : https://github.com/SuperPWA/super-progressive-web-apps-pro/commit/16950fe03208733b4fedb44c16dfb6a12cd8395d

**Comment by akshaywali** [comment]
pushed in SuperPWA  PRO 1.43
