### ISSUE TITLE
Feature Request: add Display option on the admin

### ISSUE THREAD

**Issue by kilinkis** [SuperPWA/Super-Progressive-Web-Apps#53]
Currently, the manifest Display setting is fixed to Standalone.
It would be nice if we could set that option from the admin, like the other settings.
For example to set it to "fullscreen".

Thank you!

**Comment by arunbasillal** [comment]
Hey @kilinkis 

Thanks for checking out SuperPWA!

You can currently do this using the `superpwa_manifest` filter. 

Please refer this: https://github.com/SuperPWA/Super-Progressive-Web-Apps/blob/6fe95304c84cd37009dcbfa82ecd590303b26419/public/manifest.php#L58-L93

Do let me know if you want me to write a function to do this in case you are not familiar with WordPress filters. 

Please let me know how it goes.

**Comment by kilinkis** [comment]
oh I see

would it be like adding this to the functions file?

```
$manifest['display'] = 'standalone';
$manifest = apply_filters( 'superpwa_manifest', $manifest ); 
```

thank you

**Comment by arunbasillal** [comment]
Not quite. 

Add this instead: 

```
/**
 * Change display to fullscreen in SuperPWA manifest
 * 
 * @param (array) $manifest An array containing all manifest parameters.
 * 
 * @author Arun Basil Lal
 */
function kilinkis_set_display_as_fullscreen_superpwa( $manifest ) {
	
	$manifest['display'] = 'fullscreen';
	
	return $manifest;
}
add_filter( 'superpwa_manifest', 'kilinkis_set_display_as_fullscreen_superpwa' );
```

Deactivate and reactivate SuperPWA once this is in place.

**Comment by kilinkis** [comment]
Thank you @arunbasillal !

**Comment by arunbasillal** [comment]
In SuperPWA 2.0, this is part of the UI. You can remove the custom code and simply use the option from the UI if you please. 

Of course, leaving the custom code there shouldn't be an issue as well.
