### ISSUE TITLE
Conflict issue with Onesignal notification in APK.

### ISSUE THREAD

**Issue by MohammedAkramU7** [SuperPWA/Super-Progressive-Web-Apps#531]
Ref ticket:- https://magazine3.in/conversation/279785?folder_id=21

Description:-
The Allow notification prompt is not visible in the APK when we click on bell icon.

Here is the screenshot
https://prnt.sc/CUSVFpF7FXCH

**Comment by Sanjeevsetu** [comment]
Issue does not seem valid. There was some setup problem at user end which was fixed.
