### ISSUE TITLE
Navigation bar extension conflict issue 

### ISSUE THREAD

**Issue by Sdaud1950** [SuperPWA/Super-Progressive-Web-Apps#533]
When the navigation bar extension is enabled and there is no MENU set (as shown in this screenshot: https://prnt.sc/IXsohQuktFg3), the menu items still appear at the bottom in the SuperPWA, as seen in this screenshot: https://prnt.sc/BoFcZEOHRshp.

Ref Ticket :https://magazine3.in/conversation/279917?folder_id=29

**Comment by kumawatvikas** [comment]
Ref : - https://github.com/SuperPWA/super-progressive-web-apps-pro/commit/b0f1a0f5d02b45ec36c82fa611ffac53e136c7ce
