### ISSUE TITLE
Need to add compatibility with Translatepress

### ISSUE THREAD

**Issue by 77naveenop** [SuperPWA/Super-Progressive-Web-Apps#535]
We need to add compatibility of translatepress with superpwa.

Reference user -: https://magazine3.in/conversation/290498?folder_id=23

**Comment by kumawatvikas** [comment]
Ref:- https://github.com/SuperPWA/super-progressive-web-apps-pro/commit/57622d725581941da77fc2dffec48ef4582847cc
