### ISSUE TITLE
Need to create an option to change the colour of the navigation bar icon.

### ISSUE THREAD

**Issue by Sdaud1950** [SuperPWA/Super-Progressive-Web-Apps#536]
Need to create an option to change the colour of the navigation bar icon.

Ref ticket:https://magazine3.in/conversation/290878?folder_id=29

**Comment by kumawatvikas** [comment]
Ref : -https://github.com/SuperPWA/super-progressive-web-apps-pro/commit/8825e91041fef625a17369aa690a691f63644f54
