### ISSUE TITLE
App must target Android 14 (API level 34) or higher

### ISSUE THREAD

**Issue by Sdaud1950** [SuperPWA/Super-Progressive-Web-Apps#537]
App must target Android 14 (API level 34) or higher warning on Google play console.

Ref Ticket : https://magazine3.in/conversation/263576?folder_id=29

**Comment by askcode21** [comment]
same concern: https://wordpress.org/support/topic/ios-17-4-eu-dma-changes/

**Comment by Sdaud1950** [comment]
https://magazine3.in/conversation/292950?folder_id=29

**Comment by MohammedAkramU7** [comment]
https://magazine3.in/conversation/301399?folder_id=21

**Comment by Sanjeevsetu** [comment]
This issue has been solved at our server. No need to change anything in plugin so I am closing it.
