### ISSUE TITLE
Menu button is not working in APK

### ISSUE THREAD

**Issue by MohammedAkramU7** [SuperPWA/super-progressive-web-apps#538]
Ref ticket: https://magazine3.in/conversation/279785?folder_id=21

Description:-
User creates a menu with the help of a custom code, and that menu is not clickable in the APK.

**Comment by Sanjeevsetu** [comment]
User has done some custom coding due to that issue is coming. We have to fix at user end and user needs to co-operate us

**Comment by Sanjeevsetu** [comment]
This issue is due to android limitation. I am currently closing it.
