### ISSUE TITLE
How to open internal link in new window?

### ISSUE THREAD

**Issue by mattpramschufer** [SuperPWA/Super-Progressive-Web-Apps#539]
The navigation bar addon doesn't really work or look well, and you can't control the color or styles of it.  So I am trying to figure out how I can have an internal link open in a new window like external links do.  Is that possible?  I have target="_blank" already but it does not follow that.

**Comment by Sanjeevsetu** [comment]
Hi @mattpramschufer 

Sorry for the delayed response. Do you still face the issues. Kindly contact us here https://superpwa.com/contact/
