### ISSUE TITLE
Conflict issue with Show On Scroll feature in CTA

### ISSUE THREAD

**Issue by MohammedAkramU7** [SuperPWA/super-progressive-web-apps#545]
Ref ticket: https://magazine3.in/conversation/300882?folder_id=21

Description:-
When we set up the CTA Banner Display to show on scroll, it will appear when we visit the website.

Issue video:
https://monosnap.com/direct/88a7QjYMOaYWD0zbNjbcflyTFZfIxo

**Comment by kumawatvikas** [comment]
Ref:- https://github.com/SuperPWA/super-progressive-web-apps-pro/commit/8185a15309568e8720be6f402bcddf3284554398
