### ISSUE TITLE
When the Pre-cache Automatic option is enabled, then there is an issue in the console. working fine in 2.0.28

### ISSUE THREAD

**Issue by Sdaud1950** [SuperPWA/super-progressive-web-apps#555]
When the Pre-cache Automatic option is enabled, then there is an issue in the console.

Ref screenshoot : https://prnt.sc/5LXxL0rm9PUu 

Ref Ticket : https://magazine3.in/conversation/313782?folder_id=29

**Comment by 77naveenop** [comment]
Another user -: https://magazine3.in/conversation/315426?folder_id=23
