### ISSUE TITLE
Exclude Add to home screen banner option is not working.

### ISSUE THREAD

**Issue by 77naveenop** [SuperPWA/super-progressive-web-apps#556]
When exclude the default banner via option "Exclude Add to home screen banner", it doesn't works.

Reference user -: https://magazine3.in/conversation/315126?folder_id=23

**Comment by kumawatvikas** [comment]
Ref:- https://github.com/SuperPWA/super-progressive-web-apps-pro/commit/b03b25a5d910b6f832fc9502d508d64e8df9b756

**Comment by kun18911** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.
