### ISSUE TITLE
SuperPWA Non-AMP install page's instruction 1st step is showing a <b> tag and 2nd is not translating

### ISSUE THREAD

**Issue by sajandara** [SuperPWA/super-progressive-web-apps#559]
SuperPWA Non-AMP install page's instruction 1st step is showing a <b> tag and 2nd is not translating

Ref ticket: https://magazine3.in/conversation/315117?folder_id=27

**Comment by Sanjeevsetu** [comment]
Ref commit : https://github.com/SuperPWA/super-progressive-web-apps-pro/commit/3a49fcec1a9076dec197b8d7c14acecda8219c4b

**Comment by kun18911** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.
