### ISSUE TITLE
CTA banner not working properly.

### ISSUE THREAD

**Issue by MohammedAkramU7** [SuperPWA/super-progressive-web-apps#562]
Ref ticket: https://magazine3.in/conversation/318618?folder_id=21

Description:
CTA banner appears after installed the PWA in devices.

**Comment by kumawatvikas** [comment]
Ref:- https://github.com/SuperPWA/super-progressive-web-apps-pro/commit/261d9bac38edb51be5f3abf885c9b244b9807a74
