### ISSUE TITLE
Conflict issue with Visibility extension

### ISSUE THREAD

**Issue by MohammedAkramU7** [SuperPWA/super-progressive-web-apps#566]
Ref ticket: https://magazine3.in/conversation/325921?folder_id=21

Description:
When we add pages in the Visibility Addon and save the settings, the main settings data, such as the icon, splash screen, and other content, are automatically removed

Here is the screenshot
https://prnt.sc/S2lv6aCc872l
https://prnt.sc/mAoWsdzzgA4L

**Comment by akshaywali** [comment]
pushed in PRO 1.48
