### ISSUE TITLE
If the option to display the CTA banner on IOS is unchecked, the CTA install button added using shortcode also stops working on IOS devices.

### ISSUE THREAD

**Issue by sajandara** [SuperPWA/Super-Progressive-Web-Apps#569]
If the option to display the CTA banner on IOS is unchecked, the CTA install button added using shortcode also stops working on IOS devices.

Ref ticket: https://magazine3.in/conversation/319960?folder_id=27

**Comment by akshaywali** [comment]
pushed in PRO 1.48
