### ISSUE TITLE
Function _load_textdomain_just_in_time was called incorrectly.

### ISSUE THREAD

**Issue by askcode21** [SuperPWA/super-progressive-web-apps#571]
One user reached out to us for this concern.

Reference ticket: https://wordpress.org/support/topic/function-_load_textdomain_just_in_time-was-called-incorrectly-67/

**Comment by MohammedAkramU7** [comment]
Another user: https://magazine3.in/conversation/333669?folder_id=21

**Comment by MohammedAkramU7** [comment]
Another user: https://magazine3.in/conversation/333690?folder_id=21

**Comment by akshaywali** [comment]
pushed in 2.2.33
