### ISSUE TITLE
WP 6.7.0: Translations loaded too early

### ISSUE THREAD

**Issue by robertoschwald** [SuperPWA/super-progressive-web-apps#572]
Translation loading for the super-progressive-web-apps domain was triggered too early. This is usually an indicator for some code in the plugin or theme running too early. Translations should be loaded at the init action or later. (Added in Version 6.7.0.)

It seems this was missed in #561

**Comment by Sanjeevsetu** [comment]
Hi @robertoschwald 

Thanks for reporting the bug. We are going to fix it soon and update a release.

**Comment by akshaywali** [comment]
pushed in 2.2.33
