### ISSUE TITLE
Add iOS ,,add to homescreen"-workaround prompt to plugin

### ISSUE THREAD

**Issue by tamerxkilinc** [SuperPWA/Super-Progressive-Web-Apps#58]
Hi everyone,

[Here](https://dockyard.com/blog/2017/09/27/encouraging-pwa-installation-on-ios) is a workaround for a modal which only displays on iOS devices which asks visitors to add the webapp to their homescreen. It could be easily implemented in this plugin with a YES / NO option and a field for custom text. 
There is also a JS file ready to use on GitHub: [cubiq/add-to-homescreen](https://github.com/cubiq/add-to-homescreen). PS: This is a feature no issue, but I could not open a pull request.

**Comment by Sanjeevsetu** [comment]
Hi @tamerxkilinc 

We have implemented above mentioned feature in pro extension. Just check it out once. https://superpwa.com/freevspro/
