### ISSUE TITLE
HTTP/2 support

### ISSUE THREAD

**Issue by Remzi1993** [SuperPWA/Super-Progressive-Web-Apps#59]
We have a HTTP/2 capable server, if we test with lighthouse we get the following warning:
![chrome_2018-10-11_13-21-25](https://user-images.githubusercontent.com/980950/46800641-9f67db80-cd58-11e8-9d4b-fc7c9c75f6f3.png)

**Comment by ibes** [comment]
... I doubt that the HTTP-protocol is something they plugin selects. 
That is normally something the server handles by itself - I thought.

**Comment by Remzi1993** [comment]
No, not exactly. If you make a reagust you do this with GET, you could specify header in a GET request.
May this is the issue, like you said the server should handles this by itself.

Like this:
```
<?php
// Create a stream
$opts = array(
  'http'=>array(
    'method'=>"GET",
    'header'=>"Accept-language: en\r\n" .
              "Cookie: foo=bar\r\n"
  )
);

$context = stream_context_create($opts);

// Open the file using the HTTP headers set above
$file = file_get_contents('http://www.example.com/', false, $context);
?>
```

**Comment by Remzi1993** [comment]
PS: I have checked again and this happens sometimes. You could check this for yourself.
All you need to do is use Lighthouse on Chrome and do an audit, do a couple of audits a you will also see the error/warning.

**Comment by josevarghese** [comment]
Tried multiple audits over LightHouse and cannot even notice any such errors at my end.

**Comment by Remzi1993** [comment]
You could close this. It's our problem

**Comment by josevarghese** [comment]
Glad to hear that @Remzi1993 !
