### ISSUE TITLE
Add option to enable / disable: Add to Home Screen

### ISSUE THREAD

**Issue by Remzi1993** [SuperPWA/Super-Progressive-Web-Apps#62]
Hi guys,

For some websites I would like to disable Add to Home Screen prompt. Is this even remotely possible?

This would help me, because I'm developing a lot of lead generation websites and the prompt is overlapping our call button on mobile devices. See for example: https://deslotenmaker.com

Kind Regards,

Remzi

**Comment by josevarghese** [comment]
This feature will be rolled out within our coming release. Hope you'll wait for that version.

**Comment by Remzi1993** [comment]
@josevarghese Thank you for the heads up! We're very satisfied with Super PWA!

**Comment by josevarghese** [comment]
Glad to hear that @Remzi1993 I'll keep you updated once we roll out the release . 

Have a great week ahead.

**Comment by Remzi1993** [comment]
Hi @josevarghese I would like to know if you have any update on this?

**Comment by Remzi1993** [comment]
@josevarghese Okay, thank you for the update!

**Comment by Remzi1993** [comment]
Hi @josevarghese 

I see that you guys have released version 2.0, congratulations!
In the SuperPWA settings I couldn't find an option to disable add to home screen.

Could this be because this feature will be added later?

Happy Holidays!

Kind Regards,

Remzi

**Comment by beatsk** [comment]
Hello @Remzi1993 

When will **this feature** finally be available? Our app on Google Play still shows "Add to Home Screen" :)

Regards,
beat

**Comment by Sanjeevsetu** [comment]
Hi @josevarghese & @Remzi1993 

This feature is now available in our pro extensions. just check it out https://superpwa.com/freevspro/ or contact our support via https://superpwa.com/contact/

**Comment by Remzi1993** [comment]
> Hi @josevarghese & @Remzi1993
> 
> This feature is now available in our pro extensions. just check it out https://superpwa.com/freevspro/ or contact our support via https://superpwa.com/contact/

I checked the provided website and I don't see a way to disable: Add to home screen
Also strange to put something like that behind a paywall when you literally want to disable a functionality.

**Comment by Sanjeevsetu** [comment]
@Remzi1993

I do understand your concern but we have bundle of feature inside 'call to action' and the one you talked about is also there.
