### ISSUE TITLE
Suggestion: Use Braces even when not required

### ISSUE THREAD

**Issue by mariadanieldeepak** [SuperPWA/Super-Progressive-Web-Apps#63]
As per WordPress coding standards, it is recommended to use Braces for `if` conditions even when not required.

https://make.wordpress.org/core/handbook/best-practices/coding-standards/php/#brace-style

Writing it here, so this doesn't get lost.

**Comment by arunbasillal** [comment]
I agree. 

At some spots I remember omitting it in couple of spots for readability, but you are welcome to change it if you think its relevant. 

https://github.com/SuperPWA/Super-Progressive-Web-Apps/blob/a06f52e1b0ddb74057ffb6d22545a9ae285ffe12/superpwa.php#L47-L49

https://github.com/SuperPWA/Super-Progressive-Web-Apps/blob/a06f52e1b0ddb74057ffb6d22545a9ae285ffe12/loader.php#L30-L31

**Comment by joglomedia** [comment]
+1 it is better following Wordpress coding standards

**Comment by mariadanieldeepak** [comment]
Related: #72

**Comment by arunbasillal** [comment]
I think I have covered the most obvious parts. 

We have some left in loader.php but we discussed to leave it that way for now for better readability.
