### ISSUE TITLE
Flash of unstyled content on navigation

### ISSUE THREAD

**Issue by willstocks-tech** [SuperPWA/Super-Progressive-Web-Apps#64]
Hi guys,
Every time I use my PWA between online and offline sessions, I see a pretty significant FOUC between pages. 
For instance, if I hit my homepage (https://willstocks.co.uk) and then navigate to the first post in the list, I see a plain-text rendering of my page for 0.5s before I see the actual page styled correctly. It's pretty jarring and unattractive!
If I navigate back to home then back into the post, it's fine! But if I close off the "app" (I'm running on iOS 12.1.1) go back online, navigate my site, go back offline and navigate the PWA - I see that flash between content again!

**Comment by willstocks-tech** [comment]
Not app issue - turns out it was my minification tool!!

**Comment by josevarghese** [comment]
Happy to help you @willstocks-tech over WordPress Forum. If anyone would like to know more about the discussion, have a look over [here](https://wordpress.org/support/topic/fouc-on-navigation-around-pwa/)
