### ISSUE TITLE
Is SuperPWA already support AMP?

### ISSUE THREAD

**Issue by joglomedia** [SuperPWA/Super-Progressive-Web-Apps#70]
Hi all,

it is not an issue, just curious to know whether SuperPWA also support AMP?

sorry for my bad English
thanks

**Comment by josevarghese** [comment]
Hi @joglomedia 

Good day to you. PWA support for AMP Add-on is already developed at our end and some more testing is needed before rollout. Hopefully, you can expect it overcoming versions.

Thanks

**Comment by joglomedia** [comment]
Hi @josevarghese, thank you for your answer

**Comment by Sanjeevsetu** [comment]
Hi @joglomedia 

It is there now. You can try our latest version.
