### ISSUE TITLE
Document SUPERPWA_DEV_MODE constant

### ISSUE THREAD

**Issue by mariadanieldeepak** [SuperPWA/Super-Progressive-Web-Apps#75]
As part of https://github.com/SuperPWA/Super-Progressive-Web-Apps/issues/68, the `SUPERPWA_DEV_MODE` constant is introduced. Document on the same.

@arunbasillal This issue can be handled once the Docs post type is set up. Until then, I'm assigning this to you.

Cc: @josevarghese

**Comment by arunbasillal** [comment]
Closing this since `SUPERPWA_DEV_MODE` was later removed. We will revisit this in the future if needed.
