### ISSUE TITLE
Start page 404

### ISSUE THREAD

**Issue by scottdetoffol** [SuperPWA/Super-Progressive-Web-Apps#78]
I'm using a page as the start page, but also tried setting the home page. Always get a 404 - Page Not Found when starting the app.

Manifest: ,"start_url":"\/favorites\/",

I'm using WP Super Cache, and tried deleting the cache.

**Comment by josevarghese** [comment]
Hi @scottdetoffol, 

Can you please share the website URL, so that I can look further over it and can update with more details.

**Comment by scottdetoffol** [comment]
https://www.detoffol.com/

**Comment by scottdetoffol** [comment]
Fixed the Application icon size

**Comment by josevarghese** [comment]
Seems like the prompt and all the features of offline are working. But when I inspected more into the code I noticed that the start page and offline page which you set consist of a lot of favicons (upon the favourites page) are loading out of the scope of PWA - ie; from another domain. Could you please change both the start page and offline page to any other one and let me know?

Also, I would like to know whether you've deleted any page which you set as **Start Page**, upon our settings page?

**Comment by scottdetoffol** [comment]
I changed start page to homepage and the offline page to default. 

I haven't deleted any pages.

**Comment by Sanjeevsetu** [comment]
Closing the ticket due to inactivity. Still have an issue, Please create new ticket or contact us
