### ISSUE TITLE
CDN Enabler

### ISSUE THREAD

**Issue by bigstamp** [SuperPWA/Super-Progressive-Web-Apps#79]
I've a problem where PWA dosn't seemto work on my site.

I use cdn enabler to load all my static files from a cdn and it seems to be offloading the manifest to the cdn.

When I first set up onesignal i had to add:

onesignal-free-web-push-notifications to my exclusions to stop it being offloaded, (see https://documentation.onesignal.com/docs/troubleshooting-web-push#section-cdn-enabler)

is there something I'd need to add to stop the PWA manifest from being off loaded as well.

**Comment by Sanjeevsetu** [comment]
Closing the ticket due to inactivity. Still have an issue, Please create a new ticket or contact us.
