### ISSUE TITLE
Problem Apps

### ISSUE THREAD

**Issue by yanou33** [SuperPWA/Super-Progressive-Web-Apps#80]
Bonjour,

Je rencontre un probleme avec cette application et je n'arrive pas à la faire fonctionner.
the website diane-security.fr.

**Comment by josevarghese** [comment]
Bonjour,

Bonne journée et merci d'avoir essayé SuperPWA. Je viens de regarder votre site Web et j'ai remarqué que toutes les fonctionnalités fonctionnaient parfaitement.

J'ai également testé votre site Web sur le LightHouse et il marque [100/100 pour PWA](https://builder-dot-lighthouse-ci.appspot.com/report.1545159331418.html#pwa). Félicitations!!

Pourriez-vous préciser les problèmes un peu plus en détail auxquels vous faites face, afin que je vous aide davantage

**Comment by yanou33** [comment]
![screen shot 12-18-18 at 08 05 pm](https://user-images.githubusercontent.com/45977990/50176695-615ed900-0300-11e9-8b18-df916c2b1a08.PNG)

Je ne vois pas cette app se charger sur mon mobile

**Comment by yanou33** [comment]
et pareil pour epave-enlevement-gratuit.fr qui fonctionnait également et la j'ai voulu activer les 2 modules et elle ne fonctionne pas

**Comment by josevarghese** [comment]
> Je ne vois pas cette app se charger sur mon mobile

I tested upon my mobile device and its working perfectly. Please do clear the browsing data over the browser and test it again if you are using Chrome for Android.

Regarding the screenshot which you shared -  As mentioned over the screenshot you shared,you need to improve the website to load within 10seconds by improving the Performance of website. Do have a look upon the "Performace" section on Lighthouse report.

"Your page loads too slowly and is not interactive within 10 seconds. Look at the opportunities and diagnostics in the "**Performance**" section to learn how to improve it."

**Comment by josevarghese** [comment]
> et pareil pour epave-enlevement-gratuit.fr qui fonctionnait également et la j'ai voulu activer les 2 modules et elle ne fonctionne pas

2 modules? Pouvez-vous préciser la question un peu plus en détail?

**Comment by Sanjeevsetu** [comment]
Closing the ticket due to inactivity. Still have an issue, Please create a new ticket or contact us.
