### ISSUE TITLE
409 error in console log

### ISSUE THREAD

**Issue by kkumar326** [SuperPWA/Super-Progressive-Web-Apps#85]
I'm getting this error in console log:

> GET https://testing.sciencehook.com/wp-content/plugins/super-progressive-web-apps/public/js/register-sw.js net::ERR_ABORTED 409

URL to test on: https://testing.sciencehook.com/

Please check.

**Comment by arunbasillal** [comment]
Hello @kkumar326 

This might have been a time where the dynamic service worker and manifest were not properly generated. 

Can you please try the latest version and confirm?

**Comment by kkumar326** [comment]
It's working fine now. Thanks a lot. Closing now.
