### ISSUE TITLE
Safari offline error: "Response served by service worker has redirections" 

### ISSUE THREAD

**Issue by bobmulder** [SuperPWA/Super-Progressive-Web-Apps#86]
Hello guys! 

First of all, thank you for the good plugin, great work! When the concept of PWA's will be accepted more broadly (\*cough\* Apple) the plugin will only become better!

I am developing a website which I can hardly test on Safari, but I do have one iPad (but I cannot use the debugger). The issue that I'm facing is that the offline page is not served when a page is not cached. Instead, I am receiving the error response: "Response served by service worker has redirections".

I am sorry I do not have any more information. As I told you, I am not able to debug on the iPad so I do not have any clou why this is happening. Hopefully this will be a hint for you, guys!

Kind regards!

**Comment by arunbasillal** [comment]
Hello @bobmulder 

Thanks for the kind words. Not sure if you figured it out yet.

It sounds to me like the offline page is redirected elsewhere. Can you check the offline page ( `offlinePage` ) set in the service worker (your-domain.com/superpwa-sw.js) redirects somewhere else? You can test with http://wheregoes.com

Looking forward to your feedback.

**Comment by bobmulder** [comment]
Hi @arunbasillal, thank you for your response! I've tested the offline page with WhereGoes, but the URL is not redirected. Do you have any other suggestions?

**Comment by keywinf** [comment]
Hi @bobmulder, did you find any solution to this?

**Comment by bobmulder** [comment]
Hi @keywinf, guess we are running the longest-living-issue-with-minimal-comments now :)

I'll do a new investigation soon, since I have an Apple device to test on. I'll keep you posted!

**Comment by Sanjeevsetu** [comment]
Closing the ticket due to inactivity. Still have an issue, Please create a new ticket or contact us.
