### ISSUE TITLE
Thoughts on providing alternate Manifest for iOS?

### ISSUE THREAD

**Issue by schnoggo** [SuperPWA/Super-Progressive-Web-Apps#87]
Because standalone PWA in iOS doesn't support cookies, WordPress sites with login are very problematic.
I'd like to serve up "standalone" manifest to most OS, but "browser" to iOS to solve the issue for now.

This app is being hosted on WPEngine which is a highly cached nginx environment.
I was planning on serving different manifests, but with the change to dynamically created manifest file, that's not going to work.

I don't think we can do anything at the plugin level since file requests are probably going to be cached and testing for UA OS would be cached with those.

I'm guess my best option at this point is separate site or multisite with different URLs for the iOS app.

Wondering if anyone has other ideas?

**Comment by arunbasillal** [comment]
Hello @schnoggo 

Right now on setups with `WP_CACHE` as true, files are still generated. 

Does WP Engine allow excluding files from cache? If so this can be addressed by using dynamic files and setting the display mode dynamically.

**Comment by schnoggo** [comment]
WP Engine runs nginx, so I'm sure we can do some dynamic file mapping.
The more I dig into iOS support for PWA, the less viable it becomes. Sounds like there's some [good news](https://twitter.com/mhartington/status/1089293403089784832) in the current iOS betas, so maybe 2019 is the year. :)

**Comment by josevarghese** [comment]
@schnoggo You're right - 2019 is the Year!! 

**SFViewController** will surely resolve the issue which you are facing and a lot of PWA features are coming over iOS 12.2

**Comment by Sanjeevsetu** [comment]
Closing the ticket due to inactivity. Still have an issue, Please create a new ticket or contact us.
