### ISSUE TITLE
Compatibility with Onesignal and multisite

### ISSUE THREAD

**Issue by Josimarcsilva** [SuperPWA/Super-Progressive-Web-Apps#94]
Hi,
The plugin is awesome, congratulations!
It would be very important to make onesignal and multisite network compatibility. I'm looking forward to this update.

Thank you!

**Comment by arunbasillal** [comment]
Thanks for the kind words @Josimarcsilva 
Its coming soon. In the February release hopefully.

**Comment by DBJDBJ** [comment]
Hm ok, February which year?

**Comment by AnupriyaSurapaneni** [comment]
A user is requesting to get OneSignal to work with the multisite environment in this plugin.

Need compatibility of OneSignal with multisite in SuperPWA.
Reference - https://secure.helpscout.net/conversation/1415092859/178734?folderId=4074390

**Comment by Sasirekhamarella** [comment]
One more user requesting the same "Onesignal integration with Multisite environment"

Need to add compatibility of OneSignal with multisite in SuperPWA.

Ref Ticket:  https://secure.helpscout.net/conversation/1438722220/182796?folderId=4405906

**Comment by ajeetku** [comment]
Released in 2.1.8
