### ISSUE TITLE
Travis CI Support

### ISSUE THREAD

**Issue by koconder** [SuperPWA/Super-Progressive-Web-Apps#95]
Hi All,

Is there appetite for Travis CI via PHPUnit and PHPCS for Wordpress Code Styling checks and testing. Will help with PR and cross-plugin, cross-WP/PHP version testing.

I have a number of repo's I manage a core Wordpress Plugin testing setup for, would be willing to setup a PR if others are happy for it?

Thanks

**Comment by arunbasillal** [comment]
Thanks for your input and interest @koconder 

Some sort of CI is in my horizon, haven't decided which one to use. I will revert back as I make progress. 

Thanks again.
