### ISSUE TITLE
Manifest and Service Worker missing with Docker & NGINX Proxy

### ISSUE THREAD

**Issue by ckiszka** [SuperPWA/Super-Progressive-Web-Apps#98]
I know this was discussed with NGINX host. I added:

```
rewrite ^/superpwa-manifest(-[0-9]+)?.json$ /index.php?superpwa-manifest-$1.json last;
rewrite ^/OneSignalSDKWorker.js.php$ /index.php?OneSignalSDKWorker.js-$1.php last;
rewrite ^/superpwa-sw(-[0-9]+)?.js$ /index.php?superpwa-sw.js last;
```

to the nginx proxy virtual config just as its typed. No luck. Has anyone tried using this plugin with Wordpress in a docker container and Nginx Proxy front end? 

![screen shot 2019-02-15 at 6 10 32 pm](https://user-images.githubusercontent.com/2527992/52889498-49fc6a80-314e-11e9-9224-b9179145d753.png)

NGINX Proxy -- https://github.com/jwilder/nginx-proxy 
Wordpress Docker -- https://hub.docker.com/_/wordpress/

**Comment by Sanjeevsetu** [comment]
Closing the ticket due to inactivity. Still have an issue, Please create a new ticket or contact us.
