### ISSUE TITLE
[Feature Request] Offline analytics

### ISSUE THREAD

**Issue by willstocks** [SuperPWA/Super-Progressive-Web-Apps#99]
Hi guys,

Would it be possible to include a tickbox in the options to enable "Offline Analytics" so we know how our PWA's are being used when offline? 

In simple terms, it's just a case of intercepting analytics requests, storing them and then uploading them once network is back.

https://developers.google.com/web/tools/workbox/ has a useful set of features, including this! Having the ability to "cache Google Fonts" as well would be an amazing feature for Super PWA to have!! I imagine a lot of people would love that too!!! That could even be expanded to then swap in `font-display: swap` for the Google Fonts, if the user selected the option!

**Comment by ajeetku** [comment]
Released in Version 2.1.6
